### ISSUE TITLE
Quick reference error regarding custom MySQL config file

### ISSUE THREAD

**Issue by tomzu** [MariaDB/mariadb-docker#327]
The quick reference for using a custom MySQL configuration file suggests to mount a directory over /etc/mysql/conf.d
This, however, does not work well, because although it is correct that /etc/mysql/my.cnf includes the config files in that directory, it includes the files in /etc/mysql/mariadb.conf.d **afterwards**, so the predefined settings in the files in there will overwrite any custom settings.
Currently, one solution is to mount the custom directory over /etc/mysql/mariadb.conf.d (instead of conf.d), though this way all of the predefinitions in that directory get lost.

**Comment by grooverdan** [comment]
It got a bit messy unintentionally in 10.5. [possible current solutions/workarounds](https://github.com/MariaDB/server/pull/1616#issuecomment-684831614)

**Comment by grooverdan** [comment]
Should be a bug report https://github.com/MariaDB/server/pull/1616#issuecomment-667489203 but I think we'll do another hack around the packaging in the entrypoint.

**Comment by grooverdan** [comment]
At long last, this has been corrected. Thanks @tomzu for the bug report and the reordering suggestion.

```
$  for v in 10.* ; do echo $v;podman    exec -ti mnew$v grep -r include /etc/mysql/ ; done
10.2
/etc/mysql/conf.d/mariadb.cnf:!includedir /etc/mysql/mariadb.conf.d/
/etc/mysql/my.cnf:!includedir /etc/mysql/conf.d/
10.3
/etc/mysql/my.cnf:!include /etc/mysql/mariadb.cnf
/etc/mysql/my.cnf:!includedir /etc/mysql/conf.d/
/etc/mysql/mariadb.cnf:!includedir /etc/mysql/mariadb.conf.d/
10.4
/etc/mysql/my.cnf:!include /etc/mysql/mariadb.cnf
/etc/mysql/my.cnf:!includedir /etc/mysql/conf.d/
/etc/mysql/mariadb.cnf:!includedir /etc/mysql/mariadb.conf.d/
10.5
/etc/mysql/mariadb.cnf:!includedir /etc/mysql/mariadb.conf.d/
/etc/mysql/mariadb.cnf:!includedir /etc/mysql/conf.d/
/etc/mysql/mariadb.conf.d/99-enable-encryption.cnf.preset/enable_encryption.preset:# !include this file into your my.cnf (or any of *.cnf files in /etc/my.cnf.d)
/etc/mysql/mariadb.conf.d/99-enable-encryption.cnf.preset/enable_encryption.preset:# to the .cnf file after the !include directive.
10.6
/etc/mysql/mariadb.cnf:!includedir /etc/mysql/mariadb.conf.d/
/etc/mysql/mariadb.cnf:!includedir /etc/mysql/conf.d/
/etc/mysql/mariadb.conf.d/99-enable-encryption.cnf.preset/enable_encryption.preset:# !include this file into your my.cnf (or any of *.cnf files in /etc/my.cnf.d)
/etc/mysql/mariadb.conf.d/99-enable-encryption.cnf.preset/enable_encryption.preset:# to the .cnf file after the !include directive.
```
