### ISSUE TITLE
Support starting with encrypt-tmp-files

### ISSUE THREAD

**Issue by darioseidl** [MariaDB/mariadb-docker#339]
Starting the MariaDB Docker image with `--encrypt-tmp-files=1` fails with this error:

> ERROR: mysqld failed while attempting to check config
> ...
> command was: "mysqld --verbose --help --log-bin-index=/tmp/..."
> ... Failed to enable encryption of temporary files

There exists a bug report for this on [Jira](https://jira.mariadb.org/browse/MDEV-14884), but this only affects the Docker image afaict.

As  Elena Stepanova pointed out there:

> I assume that mysqld --verbose --help does need to create a temporary file, but nothing else, hence the problem with this option specifically. 

The docker-entrypoint script runs `mysqld --verbose --help` in `mysql_check_config` and `mysql_get_config`. As a fix, I appended  `--encrypt-tmp-files=0` to those two calls in a customized entrypoint, and then I can run the image with `--encrypt-tmp-files=1`.

If that's an acceptable fix, I could create a pull request for it.

**Comment by tianon** [comment]
Ahh, that's amusing - so I guess whatever encryption key gets used for encrypting temporary files doesn't get created for `--verbose --help` :sweat_smile:

I guess this is conceptually similar to `--log-bin-index` and we should indeed add it to the list of arguments (perhaps with a link back to this issue for context).

**Comment by darioseidl** [comment]
I added a pull request that adds `--encrypt-tmp-files=0` in `mysql_check_config` and `mysql_get_config` (and a comment). Would you be willing to merge it in?

**Comment by grooverdan** [comment]
Assumed to be fixed by #340. Thanks for the contribution.

**Comment by darioseidl** [comment]
Yes, it's working already with the mariadb:10.5.9 image. Thanks!

**Comment by grooverdan** [comment]
doubly so with MDEV-14884 fixed too. I'm going to partially revert #340 now.

With MDEV-25728 in progress hopefully that will get simpler by next release too.
