### ISSUE TITLE
The CONNECT storage engine (ODBC Windows 10)

### ISSUE THREAD

**Issue by Alfa2k20** [MariaDB/mariadb-docker#361]
I give this error "OpenTable: SQLDriverConnect: [Microsoft][ODBC Driver Manager] Nome da fonte de dados não encontrado e nenhum driver padrão especificado", Translate: "OpenTable: SQLDriverConnect: [Microsoft] [ODBC Driver Manager] Data source name not found and no default driver specified" but source on excel or any app works fine.
DROP TABLE IF EXISTS teste;

CREATE TABLE es_bureau_fone_xx (
    id_teste_int bigint NOT NULL,
    teste_str varchar(20) DEFAULT NULL
) ENGINE=CONNECT
  table_type=ODBC
  tabname='pub_teste'
  CONNECTION='DSN=Teste; or CONNECTION='Driver={PostgreSQL Unicode(x64)};Server=<ip address>;Port=<port number>;Database=<db name>;UID=<username>;PWD=<password>'

give this error

**Comment by grooverdan** [comment]
If you `show engines` does it show the connect engine there?

By default the `mariadb-plugin-connect` package that provides it isn't in the mariadb containers. If you base a container of this, `apt-get -y update && apt-get install mariadb-plugin-connect` it should be there.

/etc/mysql/mariadb.conf.d/connect.cnf is a configuration file installed by the package that loads this plugin.

Also recommend listing which container you are using have when raising issues.

**Comment by Alfa2k20** [comment]
i have plugin installed and loaded

**Comment by Alfa2k20** [comment]
CONNECT, 1.7, Stable
show engines
CONNECT, Support=YES, Trans.=NO XA=NO Savepoints=NO

**Comment by an3l** [comment]
Which version of MariaDB you are using ?
Can you try to use MariaDB ODBC driver and see what is happening ?

**Comment by lawrinn** [comment]
Can that be, that DSN is defined for 32b, and not for 64b, or vice versa?

**Comment by an3l** [comment]
I'm closing this issue as a lack of information to be reproduced. 
Feel free to reopen the issue with informations: 
which mariadb you are using, which MariaDB ODBC connector you are using (in example is postgres) and show your odbc data source (version,platform and content) from odbc data source administrator.
