### ISSUE TITLE
Bind on unix socket: Permission denied

### ISSUE THREAD

**Issue by o-alquimista** [MariaDB/mariadb-docker#363]
I'm building an image based on this one using Buildah and running it with Podman. The unix socket, for some reason, is not being created with the ownership and permissions I set when building it, which causes MariaDB to fail to start.

All commands are being executed as root.

## To reproduce
1. First, I copy the client-server configuration.
```sh
container=$(buildah from docker.io/library/mariadb:10.5)

buildah copy $container ./client-server.cnf /etc/mysql/conf.d/
```

The `client-server.cnf` file has the following content:
```ini
[client-server]
socket = /var/run/mariadb/mariadb.sock
```

2. Next, I create the socket directory and set ownership and permissions.
```sh
buildah run $container -- mkdir /var/run/mariadb
buildah run $container -- chown -R mysql:user /var/run/mariadb
buildah run $container -- chmod -R 770 /var/run/mariadb
```

"user" is a user and group I create just before running the commands above. Yes, I have tested that the user and group are created successfully.

3. With the image build finished (unmount + commit), I create the pod, a volume for the database files and another volume for the unix socket (to share it with another container later).

This is the command I use to run it:
```sh
podman run -d --pod example --name mariadb --volume example_database:/var/lib/mysql/ --volume example_socket_mariadb:/var/run/mariadb/ localhost/example-mariadb
```

And the result is this:
```
2021-04-02  2:15:41 0 [ERROR] Can't start server : Bind on unix socket: Permission denied
2021-04-02  2:15:41 0 [ERROR] Do you already have another mysqld server running on socket: /var/run/mariadb/mariadb.sock ?
2021-04-02  2:15:41 0 [ERROR] Aborting
2021-04-02 02:16:12+00:00 [ERROR] [Entrypoint]: Unable to start server.
```

## My workaround
- The `example_socket_mariadb` volume will later be mounted into the container it is meant to be shared with. If, after a failed start, I go in and manually fix the permissions of the `/var/run/mariadb` directory from within another running container, the MariaDB container will start successfully after being restarted. The problem here is that the permissions are not being set during the build process for some reason; or maybe they are, but something else is changing them during runtime.

## Things I've tried
- Ran the whole build process from the shell, one step at a time, to pinpoint a failure at some point, but I found none. All commands executed correctly and the permissions of `/var/run/mariadb` were set as expected. I checked that by running:
```
buildah run $container -- ls -al /var/run/mariadb
```

However, when I run the resulting image with podman, the socket directory is owned by `root:root` instead of `mysql:user`.

Before migrating to podman, I used docker. The Dockerfile used to build this image still works, and it has the exact same instructions (in Dockerfile syntax, of course). Maybe this is something related to podman; or maybe it's something I missed; or maybe a problem with the image? I appreciate your help to figure this out.

**Comment by o-alquimista** [comment]
An update: I'm beginning to suspect this issue is also the cause of #364.

Reason: The environment variables work as expected when I don't change the default socket. If I mess with the socket, everything breaks.

**Comment by grooverdan** [comment]
The implementation is meant to detect the socket from the `mysqld --help --verbose` output  https://github.com/MariaDB/mariadb-docker/blob/master/docker-entrypoint.sh#L188.

```
root@295041b9c5a1:/# mysqld --help --verbose | grep socket
                      Buffer length for TCP/IP and socket communication
  --performance-schema-max-socket-classes=# 
                      Maximum number of socket instruments.
  --performance-schema-max-socket-instances=# 
                      Maximum number of opened instrumented sockets. Use 0 to
                      domain socket, Windows named pipe or shared memory).
                      the slave off the socket once the slave connects. Due to
                      are SSL/TLS, Unix sockets or named pipes.
  --socket=name       Socket file to use for connection
                      socket
  --unix-socket[=name] 
                      Enable or disable unix_socket plugin. One of: ON, OFF,
performance-schema-max-socket-classes                        10
performance-schema-max-socket-instances                      -1
socket                                                       /var/run/mariadb/mariadb.sock
```
This seems to be correct.

The problem you have is despite changing the permissions on /var/run/mariadb in buildah, once you run attaching the volume, its the permissions of the volume that hide what's underneath.

```
$  podman run  --name mariadb --volume example_database:/var/lib/mysql/ --volume example_socket_mariadb:/var/run/mariadb/ -ti localhost/example-mariadb bash 
root@682e6aa05006:/# ls -la /var/run/mariadb/
total 8
drwxr-xr-x. 2 root root 4096 Apr  9 00:26 .
drwxr-xr-x. 8 root root 4096 Apr  9 00:24 ..
```

You can fix the permissions in the buildah stage like:

```
$ podman inspect example_socket_mariadb
[
    {
        "Name": "example_socket_mariadb",
        "Driver": "local",
        "Mountpoint": "/home/dan/.local/share/containers/storage/volumes/example_socket_mariadb/_data",
        "CreatedAt": "2021-04-09T10:41:37.876483848+10:00",
        "Labels": {},
        "Scope": "local",
        "Options": {}
    }
]

~/repos/tests-docker 
$ ls -lad /home/dan/.local/share/containers/storage/volumes/example_socket_mariadb/_data
drwxr-xr-x. 2 dan dan 4096 Apr  9 10:41 /home/dan/.local/share/containers/storage/volumes/example_socket_mariadb/_data

~/repos/tests-docker 
$ buildah run --volume /home/dan/.local/share/containers/storage/volumes/example_socket_mariadb/_data:/var/run/mariadb/ $container -- chown mysql: /var/run/mariadb/

~/repos/tests-docker 
$ ls -lad /home/dan/.local/share/containers/storage/volumes/example_socket_mariadb/_data
drwxr-xr-x. 2 100998 100998 4096 Apr  9 10:41 /home/dan/.local/share/containers/storage/volumes/example_socket_mariadb/_data

~/repos/tests-docker 
$ buildah commit $container  example-mariadb 
Getting image source signatures
Copying blob 0e64bafdc7ee skipped: already exists  
Copying blob 935f303ebf75 skipped: already exists  
Copying blob 346be19f13b0 skipped: already exists  
Copying blob f72555674c47 skipped: already exists  
Copying blob b7c240f21d11 skipped: already exists  
Copying blob 2aaf7dca17f9 skipped: already exists  
Copying blob 5a306ab09ab9 skipped: already exists  
Copying blob bf7e0ece53bc skipped: already exists  
Copying blob bec1010c7960 skipped: already exists  
Copying blob ab2407daf9cc skipped: already exists  
Copying blob 8f5c38a7719e skipped: already exists  
Copying blob 0059db4fd4f4 skipped: already exists  
Copying blob c8a51dedbed1 done  
Copying config cfc2093e33 done  
Writing manifest to image destination
Storing signatures
cfc2093e33553a9b85136c19ceff529bc96e6b17bbd07aa3dfc807bb76eb3271

~/repos/tests-docker 
$ podman run -d -e MYSQL_ALLOW_EMPTY_PASSWORD=1   --name mariadb --volume example_database:/var/lib/mysql/ --volume example_socket_mariadb:/var/run/mariadb/ -ti localhost/example-mariadb
bd2cb42bc8d12015857858cb3b4291cd0203222ebb68c4bfdeb8010ffe90e189

~/repos/tests-docker 
$ podman logs mariadb
2021-04-09 00:55:27+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.9+maria~focal started.
2021-04-09 00:55:27+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-04-09 00:55:27+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.9+maria~focal started.
2021-04-09  0:55:27 0 [Note] mysqld (mysqld 10.5.9-MariaDB-1:10.5.9+maria~focal) starting as process 1 ...
2021-04-09  0:55:27 0 [Note] InnoDB: Uses event mutexes
2021-04-09  0:55:27 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-04-09  0:55:27 0 [Note] InnoDB: Number of pools: 1
2021-04-09  0:55:27 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2021-04-09  0:55:27 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2021-04-09  0:55:27 0 [Note] InnoDB: Using Linux native AIO
2021-04-09  0:55:27 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2021-04-09  0:55:27 0 [Note] InnoDB: Completed initialization of buffer pool
2021-04-09  0:55:27 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2021-04-09  0:55:27 0 [Note] InnoDB: 128 rollback segments are active.
2021-04-09  0:55:27 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-04-09  0:55:27 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-04-09  0:55:27 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-04-09  0:55:27 0 [Note] InnoDB: 10.5.9 started; log sequence number 45130; transaction id 20
2021-04-09  0:55:27 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2021-04-09  0:55:27 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-04-09  0:55:27 0 [Note] InnoDB: Buffer pool(s) load completed at 210409  0:55:27
2021-04-09  0:55:27 0 [Note] Server socket created on IP: '::'.
2021-04-09  0:55:27 0 [Warning] 'user' entry 'root@909232da5a75' ignored in --skip-name-resolve mode.
2021-04-09  0:55:27 0 [Warning] 'proxies_priv' entry '@% root@909232da5a75' ignored in --skip-name-resolve mode.
2021-04-09  0:55:27 0 [Note] Reading of all Master_info entries succeeded
2021-04-09  0:55:27 0 [Note] Added new Master_info '' to hash table
2021-04-09  0:55:27 0 [Note] mysqld: ready for connections.
Version: '10.5.9-MariaDB-1:10.5.9+maria~focal'  socket: '/var/run/mariadb/mariadb.sock'  port: 3306  mariadb.org binary distribution
```

**Comment by o-alquimista** [comment]
Thanks, I'll try that.

Could you explain to me why this additional work is necessary? I never had to do any of that to make it work with Docker. Also, even with podman/buildah, the official php image lets me create its socket and set its ownership/permissions without any of these additional steps.

**Comment by grooverdan** [comment]
Not sure about docker. You could run the same tests and look at the permissions on things.

php doesn't `gosu` to a different user, so the uid mapping of the volume matches what the php process is by default (root/pseudo-root).

I created #367 which I'll consider for next release that changes the ownership.

This is one case that suggests I shouldn't use `USER mysql` into the Dockerfile, which would I think correspond to best rootless practices.

**Comment by o-alquimista** [comment]
I couldn't get your suggested workaround to work.

The mariadb image build script (the workaround is near the end):
```sh
container=$(buildah from docker.io/library/mariadb:10.5)

buildah config --env MYSQL_ROOT_PASSWORD="example" $container

buildah copy $container ./path/to/config/example.cnf" /etc/mysql/conf.d/

# Create the user and group used to define the socket ownership
buildah run $container -- groupadd --gid 100000 example
buildah run $container -- adduser --no-create-home --uid 100000 --ingroup example --disabled-login --disabled-password --gecos "Example" example

# Create the socket directory
buildah run $container -- mkdir /var/run/mariadb
buildah run $container -- chown -R mysql:example /var/run/mariadb
buildah run $container -- chmod -R 770 /var/run/mariadb

# Workaround for issue 363 https://github.com/MariaDB/mariadb-docker/issues/363 (may be fixed by https://github.com/MariaDB/mariadb-docker/pull/367)
# The socket volume is created here
podman volume exists example_socket_mariadb || podman volume create example_socket_mariadb
# The mountpoint of the volume is obtained
mountpoint=$(podman volume inspect example_socket_mariadb | jq -r '.[0].Mountpoint')
# The ownership of the mountpoint is corrected
buildah run --volume "$mountpoint:/var/run/mariadb:Z" $container -- chown -R mysql:example /var/run/mariadb

# Finish build
buildah unmount $container
buildah commit $container example-mariadb
buildah rm $container
```

Then I run it with:
```
podman run -d --name mariadb --volume example_socket_mariadb:/var/run/mariadb/ localhost/example-mariadb
```

The ownership of $mountpoint is successfully being set to `mysql:example`, but the mariadb container still fails with `Bind on unix socket: Permission denied`.

**Comment by o-alquimista** [comment]
I just replaced MariaDB with the official `mysql:8` image, using the same build instructions, and it works.

Since I'd prefer to use MariaDB, I'll continue to be available to help debug this.

**Comment by o-alquimista** [comment]
I just found a better solution for my problem, and it's very simple.

Now I'm running the container with `--user` set to an arbitrary user. This results in data and socket directories that are owned by this user. I find it surprising because I didn't expect that would work out of the box.

Since my PHP process is also running as that same user, it can access the socket too. By the way, I'm using the default socket. I don't need to override that.

So, my `podman run` command will remain largely the same, with the exception of a new argument: `--user 100000:100000`.

**Comment by grooverdan** [comment]
Thanks for the feedback. I'll look at how to incorporate this into some FAQ/Docs somewhere.

**Comment by o-alquimista** [comment]
> I just found a better solution for my problem, and it's very simple.
> 
> Now I'm running the container with `--user` set to an arbitrary user. This results in data and socket directories that are owned by this user. I find it surprising because I didn't expect that would work out of the box.
> 
> Since my PHP process is also running as that same user, it can access the socket too. By the way, I'm using the default socket (`/run/mysqld/mysqld.sock`). I don't need to override that.
> 
> So, my `podman run` command will remain largely the same, with the exception of a new argument: `--user 100000:100000`.

Just an update: with newer versions of podman on Fedora Workstation 34, this no longer works. Podman must have changed something. I'm now running mariadb as the default `mysql` user.

**Comment by grooverdan** [comment]
If anything, I'd try smaller numbers. I think the uid mapping on podman rootless would overlap with such high numbers. Thanks for the update. A docs update is likely in the next few weeks and if I can cover something reliable then I will.

**Comment by david-caro** [comment]
I was having a similar error when trying to start mariadb as a rootless container, but it turned out to be an actual permissions issue, running this allowed my user to let the container bind, for future reference:
```
$ sudo sysctl -w "net.ipv4.ping_group_range=0 2000000" 
```
