### ISSUE TITLE
[buildah/podman] MYSQL_* environment variables not working as expected

### ISSUE THREAD

**Issue by o-alquimista** [MariaDB/mariadb-docker#364]
I'm using Buildah to build an image based on this one, and Podman to run it. Environment variables, such as `MYSQL_ROOT_PASSWORD`, are not working as expected. The `root` user in mariadb is not assigned with the chosen password. Instead, it remains without a password, allowing me to login by simply running `mysql -u root`.

This is how I define the env. variable:
```sh
workingcontainer=$(buildah from docker.io/library/mariadb:10.5)

buildah config --env MYSQL_ROOT_PASSWORD="example_password" $workingcontainer

# other tasks...
# unmount and commit new image
```

Then I run the local image I just created. It is actually set inside the container. I confirmed that with `echo $MYSQL_ROOT_PASSWORD` on the running mariadb container.

My guess is that there is something wrong with the entrypoint scripts that perform the initial setup. But then the same setup works as expected when I use Docker instead of Podman/Buildah.

### Things I've tried:
- Define the env. variables when running the container, in addition to defining it in the image build process:
```
podman run (...) --env MYSQL_ROOT_PASSWORD=example_password image_name
```

**Comment by o-alquimista** [comment]
Closing as not a bug. The problem originates from something else in my build setup, as I was unable to reproduce this issue with a simpler test case.

**Comment by grooverdan** [comment]
Oh good. I was starting to look and assume that the entrypoint was overwritten. I'll look at your other issue soon.

**Comment by o-alquimista** [comment]
Closing as not a bug. I can't reproduce the problem with a simpler test case. It must be something in my build setup.
