### ISSUE TITLE
Dockerfile build failing on arm64

### ISSUE THREAD

**Issue by mcfarlandry** [MariaDB/mariadb-docker#366]
Hi, I have been trying to build a new docker image from the 10.5 Dockerfile.  All I was doing is modifying one of the last lines of "EXPOSE" to 3310 instead of 3306. I am running the docker build on a Raspberry PI 4 (on Raspberry Pi OS 64-bit). I have also tried building the image without modifying anything, and it still fails. The last line it processes before it crashes is:
+ gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4

The error that occurs is:

gpg: keybox '/tmp/tmp.cyTsZrU3Dr/pubring.kbx' created
gpg: keyserver receive failed: Server indicated a failure
The command '/bin/sh -c set -eux;       
apt-get update;         
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates; 
savedAptMark="$(apt-mark showmanual)";
apt-get install -y --no-install-recommends wget;
rm -rf /var/lib/apt/lists/*; 
dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')";
wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; 
wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc";    export GNUPGHOME="$(mktemp -d)";
gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4;
gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu;
gpgconf --kill all;
rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc;
apt-mark auto '.*' > /dev/null;
[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null;
apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; 
chmod +x /usr/local/bin/gosu;   gosu --version;
gosu nobody true' returned a non-zero code: 2

I am new to building Dockerfiles so I apologize for any ignorance on my part. I searched around on the internet and I couldn't find anything to fix this exact problem.

**Comment by grooverdan** [comment]
The error is the first bit `gpg: keyserver receive failed: Server indicated a failure`

This might be temporary or a local network issue in connection to this server. Try `gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4` directly.

Not sure why you are changing the port. The inside container view of the port can be 3306 that is exposed outside the container as 3310 without rebuilding the container. Look closer at the manual on podman/docker `--publish` / `-p` option.

If you still want to change the expose port, you can:

```
FROM mariadb:10.5
EXPOSE 3310
```
And you have a new image.

Hope this helps.
