### ISSUE TITLE
volume /etc/mysql/conf.d does NOT work

### ISSUE THREAD

**Issue by ybxiang** [MariaDB/mariadb-docker#368]
According to 
$ docker run --name some-mariadb -v /my/custom:/etc/mysql/conf.d -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb:tag
from https://hub.docker.com/_/mariadb/, I run bellow command:
------
docker run --name some-mariadb -v /winter/custom:/etc/mysql/conf.d -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb:10.5
------
but, nothing in /winter/custom on the docker host, and noting in /etc/mysql/conf.d in the container!

This is the details:

root@controller1:/winter/tethrnet-forum# docker run --name some-mariadb -v /winter/custom:/etc/mysql/conf.d -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb:10.5
f21e486d3c994f70e16b1322349dfd6f770d3bb808971a7b464e5bff90cc5f06
root@controller1:/winter/tethrnet-forum# 
root@controller1:/winter/tethrnet-forum# ls /winter/custom/
root@controller1:/winter/tethrnet-forum# 
root@controller1:/winter/tethrnet-forum# docker container exec -it some-mariadb bash
root@f21e486d3c99:/# l /etc/mysql/conf.d/
root@f21e486d3c99:/# 

NOTE:
1. If I do NOT set the -v in above command, then I can see /etc/mysql/conf.d in the container.
2. only volume of /var/lib/mysql works well ( I tried other folders, all of them do NOT work):

root@controller1:/winter/tethrnet-forum# docker run --name some-mariadb2 -v /winter/mariadb-data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb:10.5
6160c8a9a8e4f4d865ba2eff64094b4b77a5dbc2bf050c20c62c61ec59a4d165
root@controller1:/winter/tethrnet-forum# 
root@controller1:/winter/tethrnet-forum# ls /winter/mariadb-data/
aria_log.00000001  aria_log_control  ib_buffer_pool  ibdata1  ib_logfile0  multi-master.info  mysql  performance_schema
root@controller1:/winter/tethrnet-forum#

**Comment by ybxiang** [comment]
It's caused by permissions. How to solve it:
(1) start the image without "-v /winter/custom:/etc/mysql/conf.d"
(2) enter the container, zip /etc/mysql as mysql-conf.tgz
(3) on the docker host, run 
      docker cp your-image-name:/etc/myusql/mysql-conf.tgz .
(4) unzip mysql-conf.tgz to docker host directory /winter/custom
(5) Now, restart your container with "-v /winter/custom:/etc/mysql"

**Comment by grooverdan** [comment]
also take note of #327

**Comment by grooverdan** [comment]
I tested this some more with:
```
$ mkdir /tmp/mariadb_config_vol
$ echo -e '[server]\ninnodb-buffer-pool-size=1G' >> /tmp/mariadb_config_vol/innodb.cnf
$ podman run -v /tmp/mariadb_config_vol:/etc/mysql/conf.d/ -e MARIADB_RANDOM_ROOT_PASSWORD=1  mariadb:10.4
2021-05-19 03:33:23+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.4.19+maria~focal started.
2021-05-19 03:33:23+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
	command was: mysqld --verbose --help --log-bin-index=/tmp/tmp.vQJM6gUzuq --encrypt-tmp-files=0
	mysqld: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 13 "Permission denied")
Fatal error in defaults handling. Program aborted

$ ls -laZ /tmp/mariadb_config_vol/
total 4
drwxrwxr-x.  2 dan  dan  unconfined_u:object_r:user_tmp_t:s0  60 May 19 13:33 .
drwxrwxrwt. 25 root root system_u:object_r:tmp_t:s0          540 May 19 13:33 ..
-rw-rw-r--.  1 dan  dan  unconfined_u:object_r:user_tmp_t:s0  36 May 19 13:33 innodb.cnf

$ podman run -v /tmp/mariadb_config_vol:/etc/mysql/conf.d/:z -e MARIADB_RANDOM_ROOT_PASSWORD=1  mariadb:10.4
2021-05-19 03:33:52+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.4.19+maria~focal started.
2021-05-19 03:33:52+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-05-19 03:33:52+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.4.19+maria~focal started.
2021-05-19 03:33:52+00:00 [Note] [Entrypoint]: Initializing database files

$ ls -laZ /tmp/mariadb_config_vol/
total 4
drwxrwxr-x.  2 dan  dan  system_u:object_r:container_file_t:s0  60 May 19 13:33 .
drwxrwxrwt. 25 root root system_u:object_r:tmp_t:s0            540 May 19 13:33 ..
-rw-rw-r--.  1 dan  dan  system_u:object_r:container_file_t:s0  36 May 19 13:33 innodb.cnf
```

The `:z` selinux directive to change permissions of the file is probably the right way to do this rather than unpacking within the volume.

Lets see if we can improve the error message.
