### ISSUE TITLE
Is the arm64 architecture build available?

### ISSUE THREAD

**Issue by hugeps** [MariaDB/mariadb-docker#373]
I'm trying to make use of this container on Raspberry Pi4 running Ubuntu and MicroK8s.
Is this image available on this architecture?

**Comment by grooverdan** [comment]
Arm64v8 images are part of this container manifest and have been for a while. http://soaphub.org/imagehub/?q=mariadb&n=library&p=1

Please report any problems.

**Comment by grooverdan** [comment]
Please reopen if you have troubles.
