### ISSUE TITLE
ENV MARIADB_VERSION 1:10.4.18+maria~focal does not work now May 8, 2021

### ISSUE THREAD

**Issue by BruceZu** [MariaDB/mariadb-docker#374]
Hi Admin guys,
`ENV MARIADB_VERSION 1:10.4.18+maria~focal` does not work now May 8, 2021
the Dockerfile should be changed to use `1:10.4.19+maria~focal` ?
Thank you

**Comment by grooverdan** [comment]
working on it to make everyone happy

**Comment by grooverdan** [comment]
10.4.19 is now release on dockerhub.
