### ISSUE TITLE
MariaDb start delay 

### ISSUE THREAD

**Issue by BartoszCoyote** [MariaDB/mariadb-docker#375]
Can we control the delay time before mariadb starts working after a container has been started?

**Comment by grooverdan** [comment]
I haven't looked at such a feature, however I'm hoping adding HEALTHCHECK In https://jira.mariadb.org/browse/MDEV-25434 will allow the container starter identify when the mariadb container is ready.

What are you trying to achieve with this delay?

**Comment by BartoszCoyote** [comment]
I would like to download the database backup and extract to the appropriate folder before the database starts.

**Comment by grooverdan** [comment]
Sounds like you need to use https://hub.docker.com/_/mariadb "Initializing a fresh instance" `/docker-entrypoint-initdb.d` to contain the data to populate the database and use this as a shared volume when the container starts.

**Comment by grooverdan** [comment]
Looks like you are happy with that. Please let us know if you have issues you cannot resolve.
