### ISSUE TITLE
Proposal for making maintaining Dockerfiles and docker-entrypoint.sh less painful

### ISSUE THREAD

**Issue by tymonx** [MariaDB/mariadb-docker#378]
Current approach requires to edit the `Dockerfile.template` file and the `docker-entrypoint.sh` script and run the `update.sh` script to generate files into each `10.X` directories. This make commit history, pull requests and reviews hard to analyze and introduce an unnecessary noise.

Proposition:
- The [bashbrew](https://github.com/docker-library/bashbrew) tool supports also the `File: <dockerfile>` entry ([source](https://github.com/docker-library/bashbrew/blob/9df92226ae134cac637af04e6d466b82f0508c84/manifest/rfc2822.go#L45)) for named Dockerfiles (like `Dockerfile.default`, `Dockerfile.alpine`) as alternative to the `Directory: <depth>` entry
- Move all commands from Dockerfile `RUN` sections to a single separate script like `build.sh` as a single source of truth
- Add minimal and simple named Dockerfiles like `Dockerfile-10.2`, `Dockerfile-10.3` and so on that will call the `build.sh` with some parameter like `build.sh 10.5.10`. They should contains only few lines like `RUN build.sh <mariadb-version>`, `EXPOSE`, `VOLUME`, `ENTRYPOINT`, `COPY` and so on
- Add the [`.dockerignore`](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file that will include only the `build.sh` and the `docker-entrypoint.sh` scripts
- Updating Docker project manifest by replacing the `Directory:` entry with the `File:` entry

New project root (or subdirectory) layout:

```plaintext
.
├── build.sh
├── docker-entrypoint.sh
├── Dockerfile-10.2
├── Dockerfile-10.3
├── Dockerfile-10.4
├── Dockerfile-10.5
├── Dockerfile-10.6
└── .dockerignore
```

The `.dockerignore` file example:

```plaintext
**
!build.sh
!docker-entrypoint.sh
```

Pros:
- No more `update.sh`
- Single source of truth for the `docker-entrypoint.sh` script (and `build.sh`)
- No unnecessary noises in commit histories, pull requests and reviews
- No file copies

If this proposal is interesting, I can prepare a Pull Request with necessary changes.

**Comment by grooverdan** [comment]
I know the update.sh isn't perfect, especially the version discovery (api in development https://mariadb.org/download/#rest-api), but for the most part it pins apt versions ([repeatability](https://github.com/docker-library/official-images/#repeatability)), has a pretty uniform Dockerfile and entrypoint across versions, and generally produces the right tags for generate-stackbrew-library.sh (part of the release process).

Thanks for the heads up on newer bashbrew features and I'll be keep on the current usefulness of the scripts as additional containers and a larger divergence in Dockerfiles between major versions occurs.

So at the moment, no thank you, but I'll let you know if things develop.

**Comment by tymonx** [comment]
I see and I agree with you. Thanks for quick response, I will gladly help in future in this particular area if there will be more MariaDB Docker variants and versions (Ubuntu, Alpine, Distroless, minimal).
