### ISSUE TITLE
Add Distroless variant

### ISSUE THREAD

**Issue by tymonx** [MariaDB/mariadb-docker#379]
It is related with my comment https://github.com/MariaDB/mariadb-docker/pull/343#issuecomment-846610520

Pros:
- Small base image size (19MB) compared to other base images
- It is based on the Debian base image. Because the default `mariadb` image is based on the Ubuntu image, to prepare a [distroless](https://github.com/GoogleContainerTools/distroless) image it requires only a multi stage build, copy necessary executables, scripts and libraries from the original image into new created distroless image
- Secure, no shell and no package manager for in-container attacks, smaller security surface attacks (less libraries/executetables)
- It uses `glibc` (no `musl` Alpine issues, no performance drops)
- Stable and mature (based on the Debian 10 distro)

I can provide a support in this area.

**Comment by grooverdan** [comment]
Noted, its a pretty good option, but unfortunately it fails the [repeatibility](https://github.com/docker-library/official-images#repeatability) criteria (like [ubi](https://github.com/docker-library/official-images/issues/9445)).

There's some back-burner issue [MDEV-13234](https://jira.mariadb.org/browse/MDEV-13234) for producing a minimal tarball image for release (that can be used with dbdeployer also). We'd be doing a static linking of maybe glibc there which solves most issues and hence considering bash or busybox as base image (though I'm not sure the de-bashifiying the entrypoint has a substantial value for effort).

What I'm mainly after from our user-base is a clear requirement(s), whether that is being smaller, a particular architecture, xyz package management or indeed something else.

**Comment by tymonx** [comment]
I see. I wasn't aware of this limitation. I have opened two other related issues in Docker official images and the Distroless project:

- https://github.com/docker-library/official-images/issues/10218
- https://github.com/GoogleContainerTools/distroless/issues/739

If one of these propositions will be accepted, I propose this simple Docker scheme tag convection `mariadb:<version>-distroless` or `mariadb:<version>-minimal` with annotation in the documentation that these images are based on the Distroless image without built-in shell and package manager.

Smaller size is one of benefits (faster downloads in CI, less occupied MBs in storage) but it has other advantages like smaller security surface attacks, less CVEs (Common Vulnerabilities and Exposures) to analyze, faster/better security audits, no in-container attacks. In microservice based, secure or enterprise applications it is very important case.

**Comment by grooverdan** [comment]
Unfortunately, this requires a resolution to docker-library/official-images#10218 before we can consider it. Thanks for raising those. We'll see how Red Hat and Google respond to the build changes for UBI (Skopeo based last time I found it) and distoless respectively.
