### ISSUE TITLE
Deprecated SKS-Keyservers DNS-Records break container build

### ISSUE THREAD

**Issue by schoenr79** [MariaDB/mariadb-docker#380]
GPG Keys could not be validated anymore, because dns records have been removed. This will break the build of the mariadb docker container.

```
This service is deprecated. This means it is no longer maintained, and new HKPS certificates will not be issued. Service reliability should not be expected.

Update 2021-06-21: Due to even more GDPR takedown requests, the DNS records for the pool will no longer be provided at all.
```
![image](https://user-images.githubusercontent.com/32950707/122935949-10b51480-d371-11eb-9b57-5271759b1c02.png)

**Comment by grooverdan** [comment]
Thanks for the bug report. Seems like just moving to the ubuntu server is the current fix (https://github.com/docker-library/wordpress/commit/f5e96ef8fe64860a81eac80766c06e1fe1554e4e).

This appears to work locally:
```
$ gpg --batch --keyserver keyserver.ubuntu.com --recv-keys 177F4010FE56CA3336300305F1656F24C74CD1D8
gpg: key F1656F24C74CD1D8: public key "MariaDB Signing Key <signing-key@mariadb.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by grooverdan** [comment]
https://github.com/MariaDB/mariadb-docker/runs/2891328474#step:5:855 all working.
