### ISSUE TITLE
10.4.20: linux/amd64 missing?

### ISSUE THREAD

**Issue by jgb** [MariaDB/mariadb-docker#381]
Hello,

when I try to build an image based on 10.4.20 with docker I get the following error:

```
Sending build context to Docker daemon  738.3MB
Step 1/4 : FROM mariadb:10.4.20
10.4.20: Pulling from library/mariadb
no matching manifest for linux/amd64 in the manifest list entries
```

The exact same thing worked fine with 10.4.19.

Greetings,

jgb

**Comment by grooverdan** [comment]
Yikes, quite right, appears to have released in arm64 only - http://soaphub.org/imagehub/?q=mariadb&n=library&p=1. I'll see how this can be corrected.

**Comment by grooverdan** [comment]
Corrected. Its there now.
