### ISSUE TITLE
Restore Root Password on running container

### ISSUE THREAD

**Issue by invertium** [MariaDB/mariadb-docker#385]
I have a running mariadb container that I was using with partdb (https://github.com/Part-DB/Part-DB)

Now somebody accidentally reset the database password on the partsdb server. Sadly I don't know where the compose file was executed from.
I don't have access to that database anymore :) I could run the bash and run:

` echo $MYSQL_ROOT_PASSWORD`

That actually gives me a password but then running mysql -uroot -p and entering the password gives me a permission denied. Since I cannot run the docker compose container again I can also not try this:
https://wolfgang.gassler.org/reset-password-mariadb-mysql-docker/

I've been trying to restore the data from within the docker container but no luck so far. I Wasn't able to stop the mysqld process in the container to restart it with the --skip-grant-tables command. 

I also tried to copy the /var/lib/mysql file to a different location and starting a new server over it but no luck. 

Any ideas on how to access the mysqld process or get the right password from within the container?

**Comment by grooverdan** [comment]
there's a mechanism in #362, it does require a restart however.

**Comment by grooverdan** [comment]
Please tell me if anything in the front page FAQ is unclear or doesn't work correctly.
