### ISSUE TITLE
utf8mb4_0900_ai_ci is missing

### ISSUE THREAD

**Issue by zigazajc007** [MariaDB/mariadb-docker#388]
utf8mb4_0900_ai_ci needs to be added and used by default on every database / table like Mysql 8.0 does.

**Comment by grooverdan** [comment]
That's a rather broad statement. What's your requirement? Migration?

The feature is missing on the server side and requested in https://jira.mariadb.org/browse/MDEV-20912. With enough votes it will probably get implemented.

Why use 0900 when 14.0.0 is available (https://www.unicode.org/Public/UCA/)?

**Comment by grooverdan** [comment]
Looking forward to your contribution. Closing because its not a docker library issues.
