### ISSUE TITLE
Can I use this version of Mariadb to deploy clusters?

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [MariaDB/mariadb-docker#389]
I saw some databases like "bitnami/ MariadB-Galera" on Docker Hub and got a bit confused, wondering if clustering can also be deployed in the current version.

**Comment by grooverdan** [comment]
The mariadb container does include the galera wsrep provider. With changes like #358 I hope the initialization is sufficiently decoupled to not interfere with runtime implementation and the container can be treated like a self contained service (with the right configuration).

Currently the automation on deployment (#377) and recovery (after a node shutdown - hard problem - suggestions welcome) currently needs more review (soon I hope) and testing.

I'm trying to be particularly cautious to ensure I understand the galera operations and interactions and ensure that no regressions are introduced. You are welcome to assist in the review of #377.

**Comment by Conmi-WhiteJoker** [comment]
> The mariadb container does include the galera wsrep provider. With changes like #358 I hope the initialization is sufficiently decoupled to not interfere with runtime implementation and the container can be treated like a self contained service (with the right configuration).
> 
> Currently the automation on deployment (#377) and recovery (after a node shutdown - hard problem - suggestions welcome) currently needs more review (soon I hope) and testing.
> 
> I'm trying to be particularly cautious to ensure I understand the galera operations and interactions and ensure that no regressions are introduced. You are welcome to assist in the review of #377.

Thank you for your answer, grooverdan.
Can I ask if there is a "docker-comemage. yml" file with the complete "environment" so THAT I can learn how to use mariadb clusters?
Or where can I find detailed documentation?
Thanks.

**Comment by Conmi-WhiteJoker** [comment]
> The mariadb container does include the galera wsrep provider. With changes like #358 I hope the initialization is sufficiently decoupled to not interfere with runtime implementation and the container can be treated like a self contained service (with the right configuration).
> 
> Currently the automation on deployment (#377) and recovery (after a node shutdown - hard problem - suggestions welcome) currently needs more review (soon I hope) and testing.
> 
> I'm trying to be particularly cautious to ensure I understand the galera operations and interactions and ensure that no regressions are introduced. You are welcome to assist in the review of #377.

Thank you for your answer and I hope the review will be completed as soon as possible.
