### ISSUE TITLE
Remote access to database not possible?

### ISSUE THREAD

**Issue by RT-Tap** [MariaDB/mariadb-docker#391]
Hi, I'm pretty new to docker and was trying to test it with a mariaDB instance.  I was hoping I could access the database from another machine from within my LAN however it seems no matter what I do or where  I search there is outdated information about changing `bind-address` to `0.0.0.0`  however that seems to be outdated because I see that `/etc/mysql/mariadb.conf.d/50-server.cnf` has a line that states
```
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
``` 
I also checked the [official documentation for deploying mariaDB with docker](https://mariadb.com/kb/en/installing-and-using-mariadb-via-docker/) however that seems to be outdated as well?  I couldn't get it to work with the instructions that were given there.

I'm using port 3366 to forward? port 3306 from the container so I dont think its a port issue.  And I also created users with specific privilege's for LAN access but that doesn't seem to be the issue as I cant even reach the server.

Any and all help is greatly appreciated.

By the way am I thinking of docker incorrectly?  It seems like a lot of effort was put into not allowing remote access to the database however I figured that was kind of the point of docker to have an instance of a piece of software that was isolated from the host but still accessible.

**Comment by grooverdan** [comment]
Continuing discussion on https://dba.stackexchange.com/questions/299373/allowing-remote-connections-to-mariadb-docker-conatiner
