### ISSUE TITLE
hub.docker.com Documents incomplete

### ISSUE THREAD

**Issue by LeamHall** [MariaDB/mariadb-docker#396]
In the "How to use this image" in https://hub.docker.com/_/mariadb, the recommended code doesn't work. It assumes a password for example-user, but doesn't give one. The root user instructions don't seem to work either, but using "root" vice "example-user", with "some-secret-pw" works.

I apologize for not offering a PR for the page, I don't know your document layout yet.

**Comment by grooverdan** [comment]
Noted. I have a moderate set of outstanding documentation things that I should address. If you don't get to this first I'll include this too.

Docs are derived from: https://github.com/docker-library/docs/tree/master/mariadb

**Comment by LeamHall** [comment]
Thanks for the URL! Let me see what I can come up with.

**Comment by LeamHall** [comment]
Since this is my first effort at contributing, would you mind giving me some feedback?

https://github.com/LeamHall/docs/commit/d027f84b746aa5df62b9ee139749dc8740bc0a99

**Comment by LeamHall** [comment]
Looks pretty fun, let me dive into it and give you some more stuff to review.

**Comment by grooverdan** [comment]
Great, squash those and send a PR to https://github.com/docker-library/docs.

I'm happy to do review other branches on PRs on that site so the Docker Library people can chip in a review too.

**Comment by LeamHall** [comment]
PR  https://github.com/docker-library/docs/pull/2055

**Comment by grooverdan** [comment]
closed by https://github.com/docker-library/docs/pull/2055

Thanks!
