### ISSUE TITLE
Initialisation of data directory changes owner to `mysql` but does not change group.

### ISSUE THREAD

**Issue by monkeyhybrid** [MariaDB/mariadb-docker#401]
In `docker-entrypoint.sh`'s `docker_init_database_dir()` function, ownership of `/var/lib/mysql` is changed to `mysql` but leaves the group as `root`.

This does not appear to be in line with MariaDB defaults found elsewhere where both user and group are changed to `mysql:mysql`.

Leaving the group as `root` makes it more awkward to have full control with bind-mounts, etc.

**Comment by monkeyhybrid** [comment]
Here's the change I currently make to `docker-entrypoint.sh` to get around this.

I change this:

```
find "$DATADIR" \! -user mysql -exec chown mysql '{}' +
```

to this:

```
find "$DATADIR" -exec chown mysql:mysql '{}' +
```
I'm doing this from a Dockerfile with:-

```
RUN sed -i 's/find "\$DATADIR" \\! -user mysql -exec chown mysql \x27{}\x27 +/find "\$DATADIR" -exec chown mysql:mysql \x27{}\x27 +/g' /usr/local/bin/docker-entrypoint.sh
```

**Comment by grooverdan** [comment]
Odd I don't see the permission difference. What container runtime are you using?

```
$ podman volume create mdata
mdata

$ podman run -v mdata:/var/lib/mysql/ -e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1  mariadb:10.6
...

$ podman ps
CONTAINER ID  IMAGE                           COMMAND               CREATED         STATUS             PORTS       NAMES
61033c7b2e2a  docker.io/library/mariadb:10.6  mariadbd              11 seconds ago  Up 11 seconds ago              bold_wing

$ podman exec -ti bold_wing ls -la /var/lib/mysql/
total 123336
drwxr-xr-x. 5 mysql mysql      4096 Nov 28 23:41 .
drwxr-xr-x. 8 root  root       4096 Nov 10 01:30 ..
-rw-rw----. 1 mysql mysql    417792 Nov 28 23:41 aria_log.00000001
-rw-rw----. 1 mysql mysql        52 Nov 28 23:41 aria_log_control
-rw-rw----. 1 mysql mysql         9 Nov 28 23:41 ddl_recovery.log
-rw-rw----. 1 mysql mysql       946 Nov 28 23:41 ib_buffer_pool
-rw-rw----. 1 mysql mysql 100663296 Nov 28 23:41 ib_logfile0
-rw-rw----. 1 mysql mysql  12582912 Nov 28 23:41 ibdata1
-rw-rw----. 1 mysql mysql  12582912 Nov 28 23:41 ibtmp1
-rw-rw----. 1 mysql mysql         0 Nov 28 23:41 multi-master.info
drwx------. 2 mysql mysql      4096 Nov 28 23:41 mysql
drwx------. 2 mysql mysql      4096 Nov 28 23:41 performance_schema
drwx------. 2 mysql mysql     12288 Nov 28 23:41 sys

~/repos/mariadb-server-10.7 bb-10.7-danielblack-systemd-galera-pr1143
$ podman exec -ti bold_wing grep find /usr/local/bin/docker-entrypoint.sh
		find "$DATADIR" \! -user mysql -exec chown mysql '{}' +
		find "${SOCKET%/*}" -maxdepth 0 \! -user mysql -exec chown mysql '{}' \;
		# no, we don't care if read finds a terminating character in this heredoc

$ podman --version
podman version 3.4.2
```

I'm ok with the change (above), though I'd like to see the case that generated this.

**Comment by grooverdan** [comment]
:ping_pong: What container environment are you using? Can you show your bind-mount scenario?

**Comment by grooverdan** [comment]
Noted this in singularity, will be fixed in the next release. Thanks for the issue report.

**Comment by monkeyhybrid** [comment]
Sorry I didn't reply earlier, I somehow missed the notifications for your comments. Sounds like you have it sorted now but feel free to give me a shout if you need more feedback. Cheers!

**Comment by grooverdan** [comment]
I'm still a little interested in the container runtime and the way you hit this so I can account for it in future testing/development.

test images on quay.io/mariadb-foundation/mariadb-devel:10.X (for X > 2) should have the changes included if you'd like to do a quick test before official images come out.

**Comment by monkeyhybrid** [comment]
I'm going to be away from the PC for  ~24 hours, but as soon as I can, I'll load up what I was working on and give you more details. I'll try out the test image too. Cheers!

**Comment by monkeyhybrid** [comment]
Just had a quick chance to try this out again. I'm fairly new to the world of Docker so please forgive me if I'm doing something daft.

My aim is to run my local web development stack (Nginx, PHP, MariaDB, etc) with Docker. For development purposes, I am bind mounting various directories rather than using volumes. This includes a bind mount for the MariaDB container's `/var/lib/mysql` directory, to make it easier for me to play about with the database files within. Not something I'd do in production but sometimes useful to me in development. To make filesystem permissions work nicely in my development environment, I change the UID and GID for the `mysql` user within the container to match the UID and GID of my local user on the host machine.

My `docker-compose.yml` contains:

```
services:
  db:
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
      args:
        UID: ${MARIADB_UID:-}
        GID: ${MARIADB_GID:-}
    volumes:
      - ./mariadb-data:/var/lib/mysql
```
Gets my UID and GID (`1000`) from `.env` containing:

```
MARIADB_UID=1000
MARIADB_GID=1000
```
And uses `./docker/mariadb/Dockerfile` to customise `mysql` user's UID+GID like so:

```
FROM mariadb:10.6

ARG UID
ARG GID

# Change mysql user's UID and GID and update file ownership accordingly.
RUN [ ${UID:-0} -ne 0 ] && \
    id -u mysql > /tmp/old-id && \
    usermod -u ${UID} mysql && \
    find / ! -path "/proc/*" -uid $(cat /tmp/old-id) -exec chown --changes --no-dereference ${UID} '{}' \+ && \
    rm /tmp/old-id
RUN [ ${GID:-0} -ne 0 ] && \
    getent group mysql | cut -d: -f3 > /tmp/old-id && \
    groupmod -g ${GID} mysql && \
    find / ! -path "/proc/*" -gid $(cat /tmp/old-id) -exec chown --changes --no-dereference :${GID} '{}' \+ && \
    rm /tmp/old-id
```
This works fine in that UID and GIDs are updated correctly for the `mysql` user and all files owned by `mysql` user and/or `mysql` group are updated accordingly.

The only issue I have is that the `/var/lib/mysql` directory itself had `root` group ownership by default, and as such does not have group ownership changed to match my specified GID. All files within there are fine though, as shown here:

```
$ docker exec -it docker-web-db-1 ls -la /var/lib/mysql

total 123340
drwxr-xr-x 6 mysql root       4096 Feb 16 11:40 .
drwxr-xr-x 1 root  root       4096 Nov 10 01:30 ..
-rw-rw---- 1 mysql mysql    417792 Feb 16 11:40 aria_log.00000001
-rw-rw---- 1 mysql mysql        52 Feb 16 11:40 aria_log_control
-rw-rw---- 1 mysql mysql         9 Feb 16 11:40 ddl_recovery.log
-rw-rw---- 1 mysql mysql       946 Feb 16 11:40 ib_buffer_pool
-rw-rw---- 1 mysql mysql 100663296 Feb 16 11:40 ib_logfile0
-rw-rw---- 1 mysql mysql  12582912 Feb 16 11:40 ibdata1
-rw-rw---- 1 mysql mysql  12582912 Feb 16 11:40 ibtmp1
-rw-rw---- 1 mysql mysql         0 Feb 16 11:40 multi-master.info
drwx------ 2 mysql mysql      4096 Feb 16 11:40 mysql
drwx------ 2 mysql mysql      4096 Feb 16 11:40 performance_schema
drwx------ 2 mysql mysql     12288 Feb 16 11:40 sys
```
This was easy for me to fix by adding something like the following to my `Dockerfile`:

```
RUN sed -i 's/find "\$DATADIR" \\! -user mysql -exec chown mysql \x27{}\x27 +/find "\$DATADIR" -exec chown mysql:mysql \x27{}\x27 +/g' /usr/local/bin/docker-entrypoint.sh
```
And now group ownership looks ok:
```
$ docker exec -it docker-web-db-1 ls -la /var/lib/mysql

total 123340
drwxr-xr-x 6 mysql mysql      4096 Feb 16 11:49 .
drwxr-xr-x 1 root  root       4096 Nov 10 01:30 ..
-rw-rw---- 1 mysql mysql    417792 Feb 16 11:49 aria_log.00000001
-rw-rw---- 1 mysql mysql        52 Feb 16 11:49 aria_log_control
-rw-rw---- 1 mysql mysql         9 Feb 16 11:49 ddl_recovery.log
-rw-rw---- 1 mysql mysql       946 Feb 16 11:49 ib_buffer_pool
-rw-rw---- 1 mysql mysql 100663296 Feb 16 11:49 ib_logfile0
-rw-rw---- 1 mysql mysql  12582912 Feb 16 11:49 ibdata1
-rw-rw---- 1 mysql mysql  12582912 Feb 16 11:49 ibtmp1
-rw-rw---- 1 mysql mysql         0 Feb 16 11:49 multi-master.info
drwx------ 2 mysql mysql      4096 Feb 16 11:49 mysql
drwx------ 2 mysql mysql      4096 Feb 16 11:49 performance_schema
drwx------ 2 mysql mysql     12288 Feb 16 11:49 sys
```
I didn't mind doing this as I understand this is not going to be an issue for most people, and is slightly peculiar to my development environment. However, I thought it strange that the default ownership was `mysql:root` where as it is `mysql:mysql` in any other environment I've looked at. I hope this doesn't seem too pedantic of me!

I just tested with your `quay.io/mariadb-foundation/mariadb-devel:10.6` image and can confirm it works great, defaulting to `mysql:mysql` ownership without me needing to do anything.

Thank you very much!

**Comment by grooverdan** [comment]
What you are doing doesn't seem daft, at least to me.

Thanks for the detail and confirmation.

I can't think of a good reason why people are going to be sharing the datadir with a shared group so, until people complain, I'm fairly happy with the change. If they do, I can look back here, compare, and see who has the more unrealistic use case.

Thanks for contributing to the MariaDB docker library.

**Comment by monkeyhybrid** [comment]
Awesome, that's great. I think if nothing else, it brings the user:group ownership inline with how the main Linux distributions are setting it.

Out of interest, at what point do commits to the MariaDB docker library make it in to the official images available on Docker Hub? Is it a case of waiting for the next point release of MariaDB?

Thanks for all your hard work!

**Comment by grooverdan** [comment]
When [this](https://github.com/docker-library/official-images/pull/11864) is merged and the CI behind that merge churn though the building of the image.

You're welcome.
