### ISSUE TITLE
macos BigSur python 3.8.0 mariadb error:  

### ISSUE THREAD

**Issue by mit-vincode** [MariaDB/mariadb-docker#402]
Hello!
macos BigSur 11.5.1
In python 3.8.0 trying to execute the command:
import mariadb

Traceback (most recent call last):
  File "/Users/bolkhovskiydmitriy/PythonData/aVision/CamGroup2/experiments/temp.py", line 2, in <module>
    import mariadb
  File "/Users/bolkhovskiydmitriy/Library/Python/3.8/lib/python/site-packages/mariadb/__init__.py", line 10, in <module>
    from ._mariadb import (
ImportError: dlopen(/Users/bolkhovskiydmitriy/Library/Python/3.8/lib/python/site-packages/mariadb/_mariadb.cpython-38-darwin.so, 2): Symbol not found: _mysql_ps_fetch_functions
  Referenced from: /Users/bolkhovskiydmitriy/Library/Python/3.8/lib/python/site-packages/mariadb/_mariadb.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/bolkhovskiydmitriy/Library/Python/3.8/lib/python/site-packages/mariadb/_mariadb.cpython-38-darwin.so

Please help fix

**Comment by grooverdan** [comment]
If this is a MariaDB Connector Python bug, please lodge it on https://jira.mariadb.org under the MariaDB Connector Python project and include which version you have installed.

Apart from having mariadb in the name too, this isn't related to the container image of docker library for mariadb (which is this project).
