### ISSUE TITLE
Creating a dump results in unterminated quoted string

### ISSUE THREAD

**Issue by rwslippey** [MariaDB/mariadb-docker#404]
I've got a database in a container I'm trying to dump.

According to the docs I should be able to run:

`docker exec some-mariadb sh -c 'exec mysqldump --all-databases -uroot -p"$MARIADB_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql`

To dump that database, however I'm getting a mysqldump error: Syntax error: unterminated quoted string

I'm thinking this might have to do with the ending quote in the command. I'm not a genius with docker but curious if mysqldump thinks that's the beginning of a quoted string. I've tired removing and I just end up with an empty .sql in the directory. 

If it helps I'm on Windows too, so that complicated things a bit.

**Comment by grooverdan** [comment]
Overall the docker command line is correct (though the `exec` before mysqldump isn't needed - I wonder why its on the official docs, I will think about it more).

As its a mysqldump error its an consequence of the SQL that mysqldump is executing. Its somehow tied to the data you have in the database and the SQL that mysqldump is generating.

Our [10.8 alpha releases in the Misc component](https://mariadb.com/kb/en/mariadb-1080-release-notes/) included improved i18n support so can you try the same dump of data with the image `quay.io/mariadb-foundation/mariadb-devel:10.8-mdev-27265-misc`  and see if you can create a mysqldump there?

Can you create a [Mariadb bug](https://jira.mariadb.org/) with the version and the output the last part of the generated output and it might be possible to deduce the next statement that is in error.
```
$ docker exec some-mariadb sh -c 'exec mysqldump --all-databases -uroot -p"$MARIADB_ROOT_PASSWORD" --log-error=/dev/stdout'
```

**Comment by grooverdan** [comment]
The improved i18n support on second thoughts may be unrelated. Reducing your test case to the table/trigger where the invalid SQL is generated by mysqldump will help significantly.  Even showing the successful output before the syntax error may be enough to predict the invalid SQL.

**Comment by grooverdan** [comment]
Please create a MariaDB bug. This relates to mysqldump (client tools) that is incompatible in a way with some of your data. This shouldn't happen. The parts of your dump before the SQL error may aid the diagnosis or help ask a very specific following question.
