### ISSUE TITLE
mariadb docker image for v10.4.23 missing

### ISSUE THREAD

**Issue by jgb** [MariaDB/mariadb-docker#411]
Hello,

I noticed the docker image for v10.4.23 isn't available yet on docker hub, can it be made available please?

Thanks!

jgb

**Comment by grooverdan** [comment]
per https://mariadb.com/kb/en/mariadb-10423-release-notes/ the release was pulled. A 10.4.24 will be released shortly with container images.

**Comment by grooverdan** [comment]
if you'd like to pre-test quay.io/mariadb-foundation/mariadb-devel:10.4 any feedback would be welcome.

Release notes above have a Docker Library section.

Docs update: https://github.com/grooverdan/docs/commit/e4eb0e185b230acc5768079aaebc897fbf3d04e7
