### ISSUE TITLE
MariaDB 10.6.7 not available via Docker Hub

### ISSUE THREAD

**Issue by kkirsche** [MariaDB/mariadb-docker#412]
Good morning,

Sorry if this is a pre-mature issue, but looking at the codebase, the 10.6 section has been updated to 10.6.7, yet Docker Hub only has 10.6.5. I know that 10.6.6 was pulled, but I have not seen that 10.6.7 was pulled, so I wanted to check if this was an error due to yanking that version.

* Docker Hub Tags: https://hub.docker.com/_/mariadb?tab=tags
* 
Thank you for your time and consideration. Sorry again if this is not applicable.

**Comment by jotoho** [comment]
The Docker Hub image being outdated is causing problems for me with nextcloud.

MariaDB 10.6.6 has a patch [for this issue](https://github.com/nextcloud/server/issues/25436) which prevents Nextcloud from working correctly.

I upgraded my MariaDB container from 10.5 to latest when I saw that MariaDB tagged 10.6.6 with the patch without realizing that the docker hub image is still outdated. I'm hesitant to attempt downgrading MariaDB back to 10.5 so I need to wait for the image to be updated.

**Comment by grooverdan** [comment]
undergoing review - https://github.com/docker-library/official-images/pull/11864

**Comment by grooverdan** [comment]
yay. finished and released

**Comment by famod** [comment]
Thanks @grooverdan!

**Comment by kkirsche** [comment]
Thank you!
