### ISSUE TITLE
Tag unstable versions differently

### ISSUE THREAD

**Issue by DerRockWolf** [MariaDB/mariadb-docker#415]
It would be nice and very helpful (e.g. for renovate) if unstable versions are tagged differently.

For example: `10.8.2-rc` or `10.8.2-unstable`.

**Comment by grooverdan** [comment]
Ok, I had removed this previously. Do you want this as an additional tag, or just part of the version tag? I don't quite understand the renovation reference.

ref: 38c1c0d4fd87abf33f824639eab9a1eeec128b8c

**Comment by DerRockWolf** [comment]
As part of the version tag would be best. Its useful for [renovate bot](https://togithub.com/renovatebot/renovate) (update automation with Pull Requests).

**Comment by grooverdan** [comment]
Can you show what would `renovate bot` config look with an ideal mariadb versioning? It seems there isn't a convention on the unstable docker tags - https://github.com/renovatebot/renovate/blob/00a2dce783478bc9e5f6ad5baf87a1da07f02a01/lib/versioning/docker/index.spec.ts.

**Comment by martadinata666** [comment]
So following this, i upvoted for RC, as it inline with how mariadb call it.
![2022-02-26-133624_453x652_scrot](https://user-images.githubusercontent.com/2433562/155832689-80c5d5ca-17e7-420d-b3fc-75d774e4f004.png)

**Comment by DerRockWolf** [comment]
> Can you show what would renovate bot config look with an ideal mariadb versioning?

There is no special configuration needed to support this versioning as Renovate treats the suffixes as compatibility indicators.
e.g.: Renovate won't update from `1.0.0-alpine` to `1.1.0` as this could destroy compatibility, on the other side it won't update from `1.0.0` to `1.2.0-rc`.

It's also possible to use strict semver for packages. This would help people who started with using e.g. `1.0.0-rc` version because with the default docker versioning they would be kept on the `rc` compatibility and won't be updated to stable releases.

renovate.json:
```json
{
  "packageRules": [
    {
      "matchPackageNames": ["mariadb"],
      "versioning": "semver"
    }
  ]
}
```
https://docs.renovatebot.com/modules/versioning/#docker-versioning
https://docs.renovatebot.com/modules/versioning/#semantic-versioning

**Comment by grooverdan** [comment]
Is this what you would be after?
```
$ ./generate-stackbrew-library.sh 
# this file is generated via https://github.com/MariaDB/mariadb-docker/blob/2937a9bd36ac208e8322c8564f069b10261749f8/generate-stackbrew-library.sh

Maintainers: Daniel Black <daniel@mariadb.org> (@grooverdan),
             Daniel Bartholomew <dbart@mariadb.com> (@dbart)
GitRepo: https://github.com/MariaDB/mariadb-docker.git

Tags: 10.8.2-rc-focal, 10.8-rc-focal, 10.8.2-rc, 10.8-rc
Architectures: amd64, arm64v8, ppc64le, s390x
GitCommit: 61c529333949a4b720c09e18da98149eec17015a
Directory: 10.8

Tags: 10.7.3-focal, 10.7-focal, 10-focal, focal, 10.7.3, 10.7, 10, latest
Architectures: amd64, arm64v8, ppc64le, s390x
GitCommit: 61c529333949a4b720c09e18da98149eec17015a
Directory: 10.7

Tags: 10.6.7-focal, 10.6-focal, 10.6.7, 10.6
Architectures: amd64, arm64v8, ppc64le, s390x
GitCommit: 61c529333949a4b720c09e18da98149eec17015a
Directory: 10.6

Tags: 10.5.15-focal, 10.5-focal, 10.5.15, 10.5
Architectures: amd64, arm64v8, ppc64le, s390x
GitCommit: 61c529333949a4b720c09e18da98149eec17015a
Directory: 10.5

Tags: 10.4.24-focal, 10.4-focal, 10.4.24, 10.4
Architectures: amd64, arm64v8, ppc64le
GitCommit: 61c529333949a4b720c09e18da98149eec17015a
Directory: 10.4

Tags: 10.3.34-focal, 10.3-focal, 10.3.34, 10.3
Architectures: amd64, arm64v8, ppc64le
GitCommit: 61c529333949a4b720c09e18da98149eec17015a
Directory: 10.3

Tags: 10.2.43-bionic, 10.2-bionic, 10.2.43, 10.2
Architectures: amd64, arm64v8, ppc64le
GitCommit: 61c529333949a4b720c09e18da98149eec17015a
Directory: 10.2
```

**Comment by grooverdan** [comment]
And what would the impacts be if say I did this tomorrow?

**Comment by DerRockWolf** [comment]
Yes, that's what I was looking for.
I think there shouldn't be a big impact. The only thing is that people who currently use `10.8.2` can't re-pull the image.

**Comment by grooverdan** [comment]
> currently use 10.8.2 can't re-pull the image

Technically the tag 10.8.2 is still there, http://soaphub.org/imagehub/?q=mariadb&n=library&p=1, its just referring to the previous image.

Those using other tags that don't have the same minor version will get updated when its not RC on I assume the next release.

Thanks for the feature request, it was in need of some good guidance on appropriate tagging for non-stable versions, so thanks for a good justification.

As you can see, its there now.
