### ISSUE TITLE
Suggested improvements to healthcheck - user / password from environment variables

### ISSUE THREAD

**Issue by tgross35** [MariaDB/mariadb-docker#416]
Thank you for implementing #94 @grooverdan, I am very happy to have it and it has some awesome capabilities, much better than most health checks out there! I ran into a handful of problems getting it implemented though, so just a few questions/suggestions:

1. This is the main thing: could the healthcheck script be updated to get the username and password from environment variables? Maybe `MARIADB_HEALTHCHECK_USER` and `MARIADB_HEALTHCHECK_PASSWORD`. I can't have password in the mariadb.cnf volume since it's in VC (which I feel is probably pretty common)  and trying to configure this with the file took some tricky trial and error.

3. It seems like there's an error in the `_test_exists` function (this was from an incorrect attempt at using the flags)
```bash
root@df17b51eae52:/# bash /usr/local/bin/healthcheck.sh --connect --defaults=healthcheck.cnf
connect
/usr/local/bin/healthcheck.sh: line 236: declare: cannot use `-f' to make functions
healthcheck unknown test 'defaults=healthcheck.cnf'
```

4. Output could use a bit more description. For example, this is a bit confusing:
```bash
root@df17b51eae52:/# bash /usr/local/bin/healthcheck.sh --connect --replication_all --defaults-extra-file=healthcheck.cnf
connect
connect
connect
```

5. Why does the order of flags seem to have an effect on whether or not the defaults-extra-file is loaded? I don't think the output of these three commands below should be different. Also a bit unclear about `replication` vs. `replication_all`, or if `replication` is a flag on its own at all.
```bash
root@df17b51eae52:/# bash /usr/local/bin/healthcheck.sh --connect --innodb_initialized --innodb_buffer_pool_loaded --replication_all --defaults-extra-file=healthcheck.cnf
connect
innodb_initialized
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
healthcheck innodb_initialized failed

root@df17b51eae52:/# bash /usr/local/bin/healthcheck.sh --connect --replication_all --defaults-extra-file=healthcheck.cnf --innodb_initialized --innodb_buffer_pool_loaded
connect
connect
connect
innodb_initialized
innodb_buffer_pool_loaded

root@df17b51eae52:/# bash /usr/local/bin/healthcheck.sh --connect --replication --defaults-extra-file=healthcheck.cnf --innodb_initialized --innodb_buffer_pool_loaded
connect
replication
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
healthcheck replication failed
```

6. I haven't found healthcheck documented anywhere. Will the readme be updated with some examples? I'm using  the following with success for now, for anyone who's looking:
```yaml
volumes:
      - "./healthcheck.cnf:/healthcheck.cnf:ro"
healthcheck:
       test: /usr/local/bin/healthcheck.sh --connect --replication_all --defaults-extra-file=healthcheck.cnf --innodb_initialized --innodb_buffer_pool_loaded
       start_period: 20s
```

My healthcheck.cnf is the following:
```ini
[mariadb-client]
user=healthcheck
password=password
```

Script to make user:
```SQL
CREATE USER 'healthcheck'@'localhost' IDENTIFIED BY 'password';
GRANT REPLICA MONITOR ON *.* TO 'healthcheck'@'localhost';
```

Unrelated - is there any chance we could get vi/vim or nano included in the main image? It comes in handy enough that I think it's worth the few MB, editing files with `>>` and `sed` isn't my strong suite.

**Comment by grooverdan** [comment]
Glad you like it. Thanks for feedback so far. Further extensions/ideas welcome.

**Comment by grooverdan** [comment]
I did do a warning as in effect every privilege is there because it grants something of security value.

Docs - probably an new markup file, current readme is bloating a bit. I may move the content to https://mariadb.com/kb. I haven't fully decided, but once its written in one form moving it is the easy bit.

Thanks for size measurements.

**Comment by tgross35** [comment]
Hm... It doesn't seem to validate the replication_ options, and something is messing with the output. I don't even see where the repeated innodb_buffer_pool_loaded echo could come from, but it seems to print once per replication flag.

```shell
# /usr/local/bin/healthcheck.sh --defaults-extra-file=/healthcheck.cnf --connect --innodb_initialized --innodb_buffer_pool_loaded --replication_io --replication_sql --replication_all --replication_xxxx --replication_io --replication
connect
innodb_initialized
innodb_buffer_pool_loaded
innodb_buffer_pool_loaded
innodb_buffer_pool_loaded
innodb_buffer_pool_loaded
innodb_buffer_pool_loaded
innodb_buffer_pool_loaded
replication
```

**Comment by grooverdan** [comment]
Output is from the `_test_exists` that I'm fixing now.

Its repeated based on:
```
--- a/healthcheck.sh
+++ b/healthcheck.sh
@@ -316,6 +316,7 @@ while [ $# -gt 0 ]; do
                        echo "healthcheck $test failed" >&2
                        exit 1
                fi
+               test=
        fi
        shift
 done
```

That test and the output was getting repeated because of this bug.

Tip to see more verbosely what is happening. `bash -x -v /usr/loca/bin/healthcheck.sh .....`

**Comment by grooverdan** [comment]
All identified bugs/enhancements (except nano, still considering) in above commit. Further suggestions welcome.

**Comment by grooverdan** [comment]
Fixes have been submitted to update the Docker Library image.

**Comment by tgross35** [comment]
Awesome, looks better already. Thanks for the changes.
