### ISSUE TITLE
Possibility for container with non persistent data

### ISSUE THREAD

**Issue by rafi0101** [MariaDB/mariadb-docker#424]
If you create a new container without volume the container creates a own volume for `/var/lib/mysql`:
https://github.com/MariaDB/mariadb-docker/blob/ad5f3827c5701c1913da7d664c77c27b579915a1/Dockerfile.template#L134

Is there any way to bypass this problem? I would like to create a MariaDB Docker container that loses all databases etc when it is recreated? I don't think you should delete the row completely as not everyone wants to lose all data when recreating, but maybe this can be solved via an environment variable whether a volume is created automatically or not?

**Comment by grooverdan** [comment]
This can be achieved already with:

<pre>
$ podman run --mount=type=tmpfs,tmpfs-size=512M,destination=/var/lib/mysql --rm -e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1  mariadb:10.5
</pre>

If you `podman exec {container} mount | grep /var/lib/mysql` you'll see its tmpfs mounted.

docker has same options.

**Comment by rafi0101** [comment]
Hi Daniel,

thank you for the quick reply. I found the related [docker compose](https://docs.docker.com/compose/compose-file/compose-file-v3/#tmpfs) guide.

Best Regards
Raphael

**Comment by kotofos** [comment]
The tmpfs solution does not work when one wants to hardcode the data (for example QA database), so it can be easily reverted on restart without extra steps.
