### ISSUE TITLE
MariaDB container throws error with mysqldump when using one-line command

### ISSUE THREAD

**Issue by anthonyma94** [MariaDB/mariadb-docker#428]
I have the official MariaDB container running on 10.7.3-focal. When I use `mysqldump` within its bash environment it works:
```
user@server:~$ docker exec -it mariadb bash
root@ee8b55b1b2cd:/# mysqldump -u root -pPASSWORD database > /var/lib/mysql/database.sql
```

But when I try to use it in one line, it throws an error:
```
user@server:~$ docker exec -it mariadb mysqldump -u root -pPASSWORD database > /var/lib/mysql/database.sql

# Returns this error
-bash: /var/lib/mysql/database.sql: No such file or directory
```

I have tried giving the command privilege and manually setting root user, via `docker exec --privileged` and `docker exec -u root` respectively. Does anyone have any suggestions?

**Comment by yosifkit** [comment]
When you do it in one line, your local bash shell first interprets the line, so file redirect (`> /var/lib/mysql/database.sql`) is interpreted from the docker host perspective, not the container. (and then you probably need to remove the `-t` to `docker run` to make sure there isn't a tty in the way)

**Comment by anthonyma94** [comment]
@yosifkit How do you suggest I approach this? I've since tried `sudo docker exec mariadb mysqldump -u root -pPASSWORD database > /docker/mariadb/database.sql`, but it's saying `Permission denied` even with sudo.

**Comment by grooverdan** [comment]
`docker exec --user mysql mariadb sh -c 'mariadb-dump -u root -pPASSWORD database > /var/lib/mysql/database.sql'` will save a mariadb-dump in `/var/lib/mysql`

**Comment by anthonyma94** [comment]
@grooverdan awesome, that's the one! I saw that in the docker docs but thought it was the outdated way of doing it or something, that's my bad. Thanks for your help!
