### ISSUE TITLE
Excessive error log warnings with healthcheck --connect

### ISSUE THREAD

**Issue by grooverdan** [MariaDB/mariadb-docker#430]
From @jerdoe in https://github.com/MariaDB/mariadb-docker/issues/94#issuecomment-1120489361

```
proj_mariadb-1  | 2022-05-08 21:10:02 1453 [Warning] Access denied for user 'root'@'127.0.0.1' (using password: NO)
proj_mariadb-1  | 2022-05-08 21:10:32 1461 [Warning] Access denied for user 'root'@'127.0.0.1' (using password: NO)
proj_mariadb-1  | 2022-05-08 21:11:03 1463 [Warning] Access denied for user 'mysql'@'127.0.0.1' (using password: NO)
proj_mariadb-1  | 2022-05-08 21:11:05 1443 [Warning] Access denied for user 'mysql'@'127.0.0.1' (using password: NO)
```

`--connect` is using TCP so `mariadb@localhost` isn't sufficient. `log_warnings=1` is one work around.

Options:
* `log_warnings=1` by default, don't want to play around too much with server defaults in containers.
* create `mysql@127.0.0.1` / `mysql@::1` users. need to give empty password otherwise same error. Which conflicts with password validation plugins.
* alternate tcp connection interfaces that doesn't complete login. Would just replace Access denied errors with connection failure errors, which would eventually be blocked and denied. This might healthcheck fail.
* replace --connect implementation with something lsof based since its in the container.

**Comment by grooverdan** [comment]
Started concept on https://github.com/MariaDB/mariadb-docker/commit/003ee866b3be88544b87c5636efa7b5cec0f1256

Its not good enough though as a health-cmd run as root cannot process the visiblity of the pid 1 file descriptors
```
root@bbd8db405ffe:/# ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
mysql          1       0  0 05:04 ?        00:00:00 mariadbd
root         326       0  0 05:06 pts/0    00:00:00 bash
root        6082     326  0 05:59 pts/0    00:00:00 ps -ef
root@bbd8db405ffe:/# lsof -t -p 1 -a -iTCP -sTCP:LISTEN
root@bbd8db405ffe:/# 
root@bbd8db405ffe:/# lsof    -p 1
COMMAND  PID  USER   FD      TYPE DEVICE SIZE/OFF NODE NAME
mariadbd   1 mysql  cwd   unknown                      /proc/1/cwd (readlink: Permission denied)
mariadbd   1 mysql  rtd   unknown                      /proc/1/root (readlink: Permission denied)
mariadbd   1 mysql  txt   unknown                      /proc/1/exe (readlink: Permission denied)
mariadbd   1 mysql    0   unknown                      /proc/1/fd/0 (readlink: Permission denied)
mariadbd   1 mysql    1   unknown                      /proc/1/fd/1 (readlink: Permission denied)
mariadbd   1 mysql    2   unknown                      /proc/1/fd/2 (readlink: Permission denied)
....
````

Alternate `ss`:
```
root@bbd8db405ffe:/# ss -nlHt state listening "( sport = :3306 )"
0                             0                                                    0.0.0.0:3306                                                0.0.0.0:*                        
0                             0                                                          *:3306                                                      *:*  
```

And the bad side is it won't part by process id. Also assuming port 3306. Parsing out `my_print_defaults` can be done, but `--port 3321` could be a container entrypoint argument.

Still looking for alternatives.

**Comment by grooverdan** [comment]
Attempted new technique of looking at `/proc/1/net/tcp{,6}`:

Seems to be working:
```
$ podman run --rm --health-cmd 'healthcheck.sh --connect' --health-interval=1s --env MARIADB_ROOT_PASSWORD=bob -d  --name m430_test  m106 ; while podman ps; do sleep 0.3; done
e57942bdc6ff7d5c57537d9a98036c27d74762266b0715335d8b816633b73ec1
CONTAINER ID  IMAGE                  COMMAND     CREATED        STATUS                       PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    3 seconds ago  Up 3 seconds ago (starting)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED        STATUS                       PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    6 seconds ago  Up 6 seconds ago (starting)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED         STATUS                        PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    10 seconds ago  Up 9 seconds ago (unhealthy)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED         STATUS                         PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    13 seconds ago  Up 12 seconds ago (unhealthy)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED         STATUS                         PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    16 seconds ago  Up 15 seconds ago (unhealthy)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED         STATUS                         PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    19 seconds ago  Up 19 seconds ago (unhealthy)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED         STATUS                       PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    22 seconds ago  Up 21 seconds ago (healthy)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED         STATUS                       PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    24 seconds ago  Up 24 seconds ago (healthy)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED         STATUS                       PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    27 seconds ago  Up 27 seconds ago (healthy)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED         STATUS                       PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    29 seconds ago  Up 29 seconds ago (healthy)              m430_test
CONTAINER ID  IMAGE                  COMMAND     CREATED         STATUS                       PORTS       NAMES
e57942bdc6ff  localhost/m106:latest  mariadbd    32 seconds ago  Up 32 seconds ago (healthy)              m430_test
```

procfs(5) for details on `/proc/{n}/net`. Relying on `0A` could be an internal state.

**Comment by grooverdan** [comment]
You're welcome. A new release is coming out soon so I'm looking to have this ready for it.

I need to think a bit more about cases where it won't work. And about the stability of a 0A state as the Linux kernel exposes.

Pros:
* determines server has reached the listening state and soon to be accepting connections
* server on shutdown closes ports early so it will report a unhealthy on shutdown
* immune from user --port and --user changes
Cons:
* a plugin that listens to a port, like galera, will also listen on a different port earlier. Hoping users use galera based healtcheck options in this case.
* hoping the /proc/pid/net/tcp interface is reasonably stable (and has been), and 0A state of the kernel is stable (and has been for a while. Is the same state exposed in WSL(2)?).
* can something else listen in /docker-entrypoint-initdb.d, currently no, as to be on pid 1 bash would need to create the listening socket, which afaik it can't do. `/dev/tcp/${HOST}/${PORT}` creates a 08 connection state.
* /proc/pid/net/tcp is the network namespace of the process, rather than the process itself, so more checks are needed as now anything that listens could trigger healthy. This has implications for different container runtimes.

@jerdoe your bug report comment was a contribution. Welcome to the community.

**Comment by grooverdan** [comment]
Unfortunately I didn't submit my change to get the warnings reduced on the server in time for the coming release (https://github.com/MariaDB/server/pull/2213). I hope to get them in the release afterwards and the container changes to accommodate them.

**Comment by gremo** [comment]
Can anyone explain to regular humans how to solve the flooding problem? I'm struggling with the same problem now, using the healthcheck script! Thanks!

**Comment by grooverdan** [comment]
so released now - see https://github.com/MariaDB/mariadb-docker/issues/512#issuecomment-1608744838
