### ISSUE TITLE
Docker secrets are not supported by the docker run

### ISSUE THREAD

**Issue by bmakan** [MariaDB/mariadb-docker#432]
According to docker documentation, secrets are only available in swarm mode. And in swarm mode, you need to use docker services, not direct containers ran by `docker run`. Therefore, unless I am missing something the following will never work:

> docker run --name some-mysql -e MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mysql-root -d mariadb:latest

It results in the following errors in logs (`docker logs <name>`):
```
2022-05-17 09:14:08+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.3+maria~focal started.
/usr/local/bin/docker-entrypoint.sh: line 36: /run/secrets/mariadb-root-password: No such file or directory
```

As a result, the entire `Docker Secrets` section of the description seems to be misleading.

**Comment by yosifkit** [comment]
It "works" as expected here. It fails because there needs to be some other mechanism to create and mount a file in the specified location in the container (like docker secrets in swarm mode, or kubernetes secrets); the env is just to tell the MariaDB entrypoint script where the file is.

```console
$ docker run --name some-mysql -e MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mysql-root -d mariadb:latest
Unable to find image 'mariadb:latest' locally
latest: Pulling from library/mariadb
d5fd17ec1767: Already exists 
49b1cc1f34f7: Pull complete 
9924a2c30493: Pull complete 
a2bb7d6219ce: Pull complete 
1eb5d2e9991e: Pull complete 
3cbaef7da880: Pull complete 
52f39675d129: Pull complete 
a4c0075a397a: Pull complete 
248a5800afac: Pull complete 
27261e54ed45: Pull complete 
3b18f8f83243: Pull complete 
Digest: sha256:07e06f2e7ae9dfc63707a83130a62e00167c827f08fcac7a9aa33f4b6dc34e0e
Status: Downloaded newer image for mariadb:latest
c031633acc9e1db5c5f322d56bf4630e7e0120a270a7e580aab8a091b5fadccb
$ docker logs some-mysql 
2022-05-17 16:14:35+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.3+maria~focal started.
/usr/local/bin/docker-entrypoint.sh: line 36: /run/secrets/mysql-root: No such file or directory
```

**Comment by grooverdan** [comment]
I've run out of space on the docker library documentation page, but when its moved, I'll expand the description a bit more.
