### ISSUE TITLE
Mariadb doesn't start the mysql server in docker

### ISSUE THREAD

**Issue by DARKBOW923** [MariaDB/mariadb-docker#433]
Hello guys, 

Basically i made a docker-compose.yml:

`version: "3.9"
services:
        mariadb:
                image: mariadb:latest
                deploy:
                  placement:
                   constraints: [node.role == worker]
                  replicas: 1
                tty: true
                ports:
                        - 3333:3306
                networks:
                 - red_mariadb
                volumes:
                    - volumen1234:/var/lib/mysql/
                environment:
                   - MARIADB_ROOT_PASSWORD=smx
                   - MARIADB_USER=smx

volumes:
  volumen1234:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.56.25,rw,vers=3"
      device: ":/export/mariadb"

networks:
 red_mariadb:
  external: true`
As you can see, the docker is correct, however when i try to enter mysql it says the following error:

`ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)`

And if i look at the logs, i see this error:

`2022-05-21 17:44:53 0 [ERROR] mariadbd: Can't lock aria control file '/var/lib/mysql/aria_log_control' for exclusive use, error: 37. Will retry for 30 seconds`

Any help? I'm using mariadb official image for docker.

**Comment by grooverdan** [comment]
this error, almost always, is another mariadb container running on the same volume.

**Comment by DARKBOW923** [comment]
> this error, almost always, is another mariadb container running on the same volume.

Its not, i just have only a mariadb container.

**Comment by grooverdan** [comment]
```
$ podman run --rm mariadb perror 37
OS error code  37:  No locks available
```

So its looking more like your nfs storage doesn't have a locking service running or its somehow disabled. There's currently no mariadb option to skip the locking on Aria control files.

**Comment by masiton** [comment]
Why is this closed? I'm encountering the same thing, there is no workaround?

**Comment by grooverdan** [comment]
please provide details of a the environment which it occurs along with container logs.

**Comment by redfast00** [comment]
@grooverdan this happens when the mariadb container triggers the OOM killer; the process will be killed by the kernel, and the lock file will still be left

**Comment by redfast00** [comment]
Yes, I've seen this happen multiple times now; issue is fixed when I delete the aria_log_control file. This was just for you information, I've 'fixed' this by having a sysadmin add more RAM to our VM.
