### ISSUE TITLE
'mariadb:latest' shows "Can't initialize timers"

### ISSUE THREAD

**Issue by yahonda** [MariaDB/mariadb-docker#434]
### Steps to reproduce
1. Install Docker on Ubuntu 22.06 x86_64 

```
$ docker -v
Docker version 20.10.6, build 370c289
$ more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```
2. Docker run using "mariadb:latest"
```
docker run --name mariadbtest -e MYSQL_ROOT_PASSWORD=mypass -p 3306:3306 -d docker.io/library/mariadb:latest
```

3. Login to the container
```
docker exec -it mariadbtest bash
```

### Expected behavior
`docker exec -it mariadbtest bash` should open bash prompt.

### Actual behavior
`Error response from daemon: Container`.

Here are actual log files.

```
$ docker run --name mariadbtest -e MYSQL_ROOT_PASSWORD=mypass -p 3306:3306 -d docker.io/library/mariadb:latest
Unable to find image 'mariadb:latest' locally
latest: Pulling from library/mariadb
125a6e411906: Pull complete
a28b55cc656d: Pull complete
f2325f4e25a1: Pull complete
c6c2d09f748d: Pull complete
af2b4ed853d2: Pull complete
8394ac6b401e: Pull complete
5b150cf0c5a7: Pull complete
1b11b2e20899: Pull complete
3d35790a91d9: Pull complete
5e73c7793365: Pull complete
3d34b9f14ede: Pull complete
Digest: sha256:3a24e9e99882a6848c5793f36ec7a730a8d301c5175613cd22a341fc039bd10a
Status: Downloaded newer image for mariadb:latest
9ca954cada2e147344469c3a376e1a3a760c5e7acd5f19565fdb5975b4237af1
```

```
$ docker exec -it mariadbtest bash
Error response from daemon: Container 9ca954cada2e147344469c3a376e1a3a760c5e7acd5f19565fdb5975b4237af1 is not running
```

```
$ docker logs -f mariadbtest
2022-05-24 02:39:15+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.8.3+maria~jammy started.
2022-05-24 02:39:15+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
	command was: mariadbd --verbose --help --log-bin-index=/tmp/tmp.kMff4dllgU
	Can't initialize timers
$
```

### Additional information
This environment can run 'mariadb:10.7' as follows.

```
$ docker run --name mariadbtest -e MYSQL_ROOT_PASSWORD=mypass -p 3306:3306 -d docker.io/library/mariadb:10.7
Unable to find image 'mariadb:10.7' locally
10.7: Pulling from library/mariadb
d5fd17ec1767: Pull complete
49b1cc1f34f7: Pull complete
9924a2c30493: Pull complete
a2bb7d6219ce: Pull complete
1eb5d2e9991e: Pull complete
3cbaef7da880: Pull complete
52f39675d129: Pull complete
01e063a0d770: Pull complete
50fb616a753d: Pull complete
36bc0be24a08: Pull complete
5afe25c59347: Pull complete
Digest: sha256:85fbfe23f9b710d21c76832ae4df096c58db0f63d5a040beea3e1e935ad39ca3
Status: Downloaded newer image for mariadb:10.7
b82cffa4918860ad75bd0b46a01cb412b152a938d280cacab9fe1d2d2a175c81
```

```
$ docker exec -it mariadbtest bash
root@b82cffa49188:/# mysql -uroot -pmypass
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 10.7.4-MariaDB-1:10.7.4+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select version();
+-------------------------------------+
| version()                           |
+-------------------------------------+
| 10.7.4-MariaDB-1:10.7.4+maria~focal |
+-------------------------------------+
1 row in set (0.000 sec)

MariaDB [(none)]> quit
Bye
root@b82cffa49188:/#
```

**Comment by grooverdan** [comment]
Thanks for the bug report.

"Can't initialize timers" is caused by a failure to create a thread. Although its a 64k thread size on this thread, its the [same in 10.7](github.com/mariaDB/server/commit/ad17c98dd5877ededb8ac3d4e0ac1f7beed5406c). I haven't identified the difference yet but am looking.

I see your docker compose yaml configuration is quite basic](https://github.com/rails/buildkite-config/blob/main/docker-compose.yml#L103).

**Comment by yahonda** [comment]
Thanks for the reply. I'm not familiar with MariaDB internal,
 the first error message is something like failing "to check config", not stack size itself.

```
2022-05-24 02:39:15+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
```

**Comment by grooverdan** [comment]
The entrypoint uses `mariadbd --help --verbose` to examine the config. Yes its odd that the `--help --verbose` needs to initialize timers, which is another thing to get addressed.

Have you only seen this in your Buildkite environment currently?

**Comment by yahonda** [comment]
> Have you only seen this in your Buildkite environment currently?

CI against MariaDB has been failing since Mon 23rd May 2022 at 20:59 UTC.

The last successful build has been created Mon 23rd May 2022 at 16:47 UTC
https://buildkite.com/rails/rails/builds/86701#2f3a5396-4237-47a5-b27c-cf6774c90bb6

The first failing build has been created Mon 23rd May 2022 at 20:59 UTC
https://buildkite.com/rails/rails/builds/86711#ebc53e55-14aa-4abf-819b-5928cbbe9938

Then I attemp to reproduce this failure locally and found `docker run --name mariadbtest -e MYSQL_ROOT_PASSWORD=mypass -p 3306:3306 -d docker.io/library/mariadb:latest` fails in my local Ubuntu 22.04 environment.

Does this answer your question?

**Comment by grooverdan** [comment]
Yep. The container release was very recent so those times correspond well. Ubuntu-22.04 is a common factor that needs to be explored.

**Comment by yahonda** [comment]
> Ubuntu-22.04 is a common factor that needs to be explored.

Agreed.

`mariadb:latest` runs successfully on my macOS(M1)

```
% sw_vers
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G5027d
%
```

```
% docker -v
Docker version 20.10.14, build a224086
% docker run --name mariadbtest -e MYSQL_ROOT_PASSWORD=mypass -p 3306:3306 -d docker.io/library/mariadb:latest
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
% docker run --name mariadbtest -e MYSQL_ROOT_PASSWORD=mypass -p 3306:3306 -d docker.io/library/mariadb:latest
Unable to find image 'mariadb:latest' locally
latest: Pulling from library/mariadb
b84950154c18: Pull complete
b1ae07faadba: Pull complete
46428e702eff: Pull complete
0e775e0ed5a0: Pull complete
031c54d0d9d9: Pull complete
602265dc68e1: Pull complete
3d1d131fb6cb: Pull complete
3a33ea1b3043: Pull complete
9539c6148f07: Pull complete
38aa29868643: Pull complete
3702214dffba: Pull complete
Digest: sha256:3a24e9e99882a6848c5793f36ec7a730a8d301c5175613cd22a341fc039bd10a
Status: Downloaded newer image for mariadb:latest
a292292472524ff9eee0c98ccfadbfa017f4ccdc74535e3c2778bff013edb1d1
% docker exec -it mariadbtest bash
root@a29229247252:/# mysql -uroot -pmypass
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 10.8.3-MariaDB-1:10.8.3+maria~jammy mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select version();
+-------------------------------------+
| version()                           |
+-------------------------------------+
| 10.8.3-MariaDB-1:10.8.3+maria~jammy |
+-------------------------------------+
1 row in set (0.002 sec)

MariaDB [(none)]> quit
Bye
root@a29229247252:/#  
```

**Comment by martadinata666** [comment]
there is some docker compability issues, i think i saw this somewhere that it need docker 20.10.10+ version

**Comment by yahonda** [comment]
Followed the steps https://docs.docker.com/engine/install/ubuntu/ to upgrade Docker version to `Docker version 20.10.16, build aa7e414`, `mariadb:latest` works in my local environment.


```
$ more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
$ docker -v
Docker version 20.10.16, build aa7e414
$ docker run --name mariadbtest -e MYSQL_ROOT_PASSWORD=mypass -p 3306:3306 -d docker.io/library/mariadb:latest
Unable to find image 'mariadb:latest' locally
latest: Pulling from library/mariadb
125a6e411906: Pull complete
a28b55cc656d: Pull complete
f2325f4e25a1: Pull complete
c6c2d09f748d: Pull complete
af2b4ed853d2: Pull complete
8394ac6b401e: Pull complete
5b150cf0c5a7: Pull complete
1b11b2e20899: Pull complete
3d35790a91d9: Pull complete
5e73c7793365: Pull complete
3d34b9f14ede: Pull complete
Digest: sha256:3a24e9e99882a6848c5793f36ec7a730a8d301c5175613cd22a341fc039bd10a
Status: Downloaded newer image for mariadb:latest
8eb1bee44896307de105effe4e07be81286247add3cd4ca63a2ffdbc5a545195
```

```
yahonda@myryzen:~$ docker exec -it mariadbtest bash
root@8eb1bee44896:/# mysql -uroot -pmypass
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 10.8.3-MariaDB-1:10.8.3+maria~jammy mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select version();
+-------------------------------------+
| version()                           |
+-------------------------------------+
| 10.8.3-MariaDB-1:10.8.3+maria~jammy |
+-------------------------------------+
1 row in set (0.000 sec)

MariaDB [(none)]> quit
Bye
root@8eb1bee44896:/# exit
exit
$
```

**Comment by grooverdan** [comment]
@martadinata666 if you can remember some references that would be appreciated.

**Comment by martadinata666** [comment]
This one [linuxserver FAQ](https://docs.linuxserver.io/faq)

Im not really sure it the same, because it specifically told `Some x86_64 hosts running older versions of the Docker engine are not compatible with some images based on Ubuntu Jammy.`, but the symptoms are alike `can't create thread`. So i assume may the same root cause.

**Comment by yahonda** [comment]
Let me contact with BuildKite to see if they can upgrade Docker version to 20.10.10 or higher.

**Comment by grooverdan** [comment]
I just pinged their slack channel of the issue.

**Comment by jradtilbrook** [comment]
Hey fine folks, just popping in here to mention the newest version of the Buildkite Elastic CI Stack is using [Docker 20.10.14](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/v5.8.2/packer/linux/scripts/install-docker.sh#L4). Perhaps the stack needs updating to pull in the newer AMI with the updated docker version?

**Comment by AndreG-P** [comment]
We are running `Debian 4.19.171-2 (2021-01-30) x86_64` with Docker `Docker version 19.03.13, build 4484c46d9d` and have the same issue with the latest mariadb image.

**Comment by grooverdan** [comment]
proposal:

https://github.com/MariaDB/mariadb-docker/compare/master...grooverdan:focal_images?expand=1

+ manually generated diff for https://github.com/docker-library/official-images
```
diff --git a/library/mariadb b/library/mariadb
index cd51229fc..0afe995f2 100644
--- a/library/mariadb
+++ b/library/mariadb
@@ -9,11 +9,21 @@ Architectures: amd64, arm64v8, ppc64le, s390x
 GitCommit: c0d07be9ad5eb3bc212c6805cc8031308c56e9b6
 Directory: 10.9
 
+Tags: 10.9.1-rc-focal, 10.9-rc-focal
+Architectures: amd64, arm64v8, ppc64le, s390x
+GitCommit: ae6c6a6891e1fc887e96898f94e8a4b8495d8289
+Directory: 10.9-focal
+
 Tags: 10.8.3-jammy, 10.8-jammy, 10-jammy, jammy, 10.8.3, 10.8, 10, latest
 Architectures: amd64, arm64v8, ppc64le, s390x
 GitCommit: c0d07be9ad5eb3bc212c6805cc8031308c56e9b6
 Directory: 10.8
 
+Tags: 10.8.3-focal, 10.8-focal, 10-focal, latest-focal
+Architectures: amd64, arm64v8, ppc64le, s390x
+GitCommit: ae6c6a6891e1fc887e96898f94e8a4b8495d8289
+Directory: 10.8-focal
+
 Tags: 10.7.4-focal, 10.7-focal, 10.7.4, 10.7
 Architectures: amd64, arm64v8, ppc64le, s390x
 GitCommit: c6d3396be642bbc73cd14b93e62c615e242f5a0d

```

The jammy base finally exposing liburing (because of available user space libraries) based capabilities of mariadb to the Docker Library users for the first time. I'm trying to avoid a full revert to focal if possible.

So the result is users that hit this can use `mariadb:latest-focal`.

@yosifkit, @tianon, do you have a suggested approach?

**Comment by MichaelUray** [comment]
I had the same issue with `mariadb:latest`, running a docker-compose file with Nextcloud:
```
nc-mariadb  | 2022-05-24 12:45:14+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.8.3+maria~jammy started.
nc-redis    | 1:C 24 May 2022 12:45:14.954 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
nc-redis    | 1:C 24 May 2022 12:45:14.954 # Redis version=7.0.0, bits=64, commit=00000000, modified=0, pid=1, just started
nc-redis    | 1:C 24 May 2022 12:45:14.954 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
nc-mariadb  | 2022-05-24 12:45:15+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
nc-mariadb  |   command was: mariadbd --character-set-server=utf8 --collation-server=utf8_unicode_ci --connect-timeout=10 --max-connections=1000 --max-allowed-packet=64M --thread-cache-size=600 --sort-buffer-size=8M --bulk-insert-buffer-size=32M --tmp-table-size=512M --max-heap-table-size=4096M --query-cache-limit=8M --query-cache-size=128M --query-cache-type=0 --long-query-time=10 --expire-logs-days=10 --max-binlog-size=100M --innodb-buffer-pool-size=512M --innodb-log-buffer-size=64M --innodb-file-per-table=1 --innodb-open-files=400 --innodb-io-capacity=400 --innodb-flush-method=O_DIRECT --innodb_read_only_compressed=OFF --verbose --help --log-bin-index=/tmp/tmp.DnHVTCcBBw
nc-mariadb  |   Can't initialize timers
```

I changed `image: mariadb` to `image: mariadb:10.7` to pin it down to the older version to get my Nextcloud back up and running.

**Comment by yahonda** [comment]
In the meantime, Rails CI uses `mariadb:10.7` https://github.com/rails/rails/issues/45167#issuecomment-1135603308

**Comment by grooverdan** [comment]
`--security-opt seccomp=unconfined` is probably also  a work around.

**Comment by quent1-fr** [comment]
Same problem here. `mariadb:10` (currently `mariadb:10.8.3`) fails to start, but not`mariadb:10.8.2` .

**Comment by yahonda** [comment]
The original issue has been identified and addressed so I think I can close this issue.

**Comment by grooverdan** [comment]
Thanks @yahonda.

As a favour request from all participants here, those running mariadb in CI/test systems, can you please use the `quay.io/mariadb-foundation/mariadb-devel:10.X` image described here https://mariadb.org/new-service-quay-io-mariadb-foundation-mariadb-devel/ (note the version hack has been removed so there are no functional differences to the next docker library release). The image `quay.io/mariadb-foundation/mariadb-devel:10.X` is updated frequently with finished code in the MariaDB server. It also pulls the latest version of the the container packaging from this repository.

Even using `quay.io/mariadb-foundation/mariadb-devel:10.7` until you have `jammy` compatible runtime would be appreciated.

At the time RC images [are announced (like 10.9.1)](https://mariadb.com/kb/en/mariadb-1091-release-notes/), adding `quay.io/mariadb-foundation/mariadb-devel:10.9` to your CI to ensure we don't hurt our mutual users on final release would be appreciated. 

The frequent and early use of this could have identified ahead of time the problems of older container runtimes. While at MariaDB we do our own testing, surprise issues like this show that is isn't complete. The inclusion of latest version server code also provide us the opportunity to revert regressions before releases [when reported](https://jira.mariadb.org).

Thanks for your support, and I'll do the best support I can on the container side.

**Comment by macropin** [comment]
@AddoSolutions CentOS 7 works if you apply an updated seccomp profile when starting eg `docker run --security-opt seccomp=/etc/docker/profiles-seccomp-scmp-act-trace.json`.

**Comment by bachoo786** [comment]
so I am on the latest version on docker compose and I have tried using the latest version of mariadb however I get the same errors as the OP. Can someone please help?

```
Docker Compose version v2.15.1
Docker version 20.10.9, build c2ea9bc
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

**Comment by bachoo786** [comment]
> @bachoo786 to summarize the solutions above (from https://docs.linuxserver.io/faq):
> 
> * Upgrade your Docker engine install to at least version 20.10.10
> * relax `seccomp=unconfined` in compose or docker when running the image
> * and from [above](https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1164078267), run with an updated `seccomp` profile

I can do the update thought I did install the latest docker engine but anyway will do it again.

However the other 2 items on the list I have got no clue on how to do them. All I know is how to run a docker image from my yaml file. I am running docker compose and not docker if that helps?

**Comment by martadinata666** [comment]
docker compose is a definitions to run docker images, it talk to docker, `hey run this`. and the docker itself it different.
usually use this method to always get latest version [docker install](https://docs.docker.com/engine/install/ubuntu/)
