### ISSUE TITLE
Is it possible to use hostname or domain name for wsrep_node_address?

### ISSUE THREAD

**Issue by chengkuangan** [MariaDB/mariadb-docker#435]
I think this question should go to the MariaDB/Server repo but the permission to open issue is disabled for normal user like me :-)

I am running MariaDB cluster with Galera in Kubernetes. I am planning to spin a Docker MariaDB instance on a RPI4 ubuntu node as an always "running" instance so that I can easily bring down my k8s without loosing the cluster state. 

Since my k8s is using `Ingress Controller` with `NodePort`. I wonder can I configure the k8s Mariadb instance to use fixed domain name instead of IP at `wsrep_node_address`. The auto discovered IP address is an internal k8s IP which is not resolvable by the external MariadDB at the RPI4 Ubuntu node. This domain name will be handled by Nginx Ingress Controller in this case.

As I noticed in the MariaDB log, all current communications between the instances are done via IP addresses(private k8s IP).

The only disadvantage of this is that the MariaDB replications and state traffics have to go a big round : 
RPI4 mariadb -> external haproxy -> k8s nginx -> k8s mariadb

I wonder how is this being done in the real life production implementation?

**Comment by grooverdan** [comment]
Its not just you, there aren't issues enabled on MariaDB/server to encourage bugs to [jira](https://jira.mariadb.org) and [help](https://mariadb.com/kb/en/getting-help-with-mariadb/) to other forums.

It seems from the validation [here](https://github.com/MariaDB/server/blob/10.9/sql/wsrep_utils.h#L100) that hostnames are allowed.

If anything isn't right to make a k8s deployment of MariaDB please do create a [bug report](https://jira.mariadb.org).
