### ISSUE TITLE
Problem with MariaDB Time and Date

### ISSUE THREAD

**Issue by Chris91550** [MariaDB/mariadb-docker#440]
Hello ! I've got a problem with my mariadb the time and data are not correct i've set the Timezone that I wanted but there is no changes:

The wrong date and time
![image](https://user-images.githubusercontent.com/99281871/173858339-812b21ae-9669-4f0f-98dc-456aec675700.png)

The correct date and time
![image](https://user-images.githubusercontent.com/99281871/173858543-cef5092c-5f4f-4273-bcab-a43436559c46.png)

**Comment by grooverdan** [comment]
```
$ podman run --rm  --env MARIADB_ROOT_PASSWORD=bob --name m106 -d mariadb:10.6 --default-time-zone=Europe/Paris
015391a31f28d9c5391972f2be95d046b9ec43e5530ffd67fbeb58cee043f9a8

$ podman exec m106 mysql -pbob -e 'select now()'; TZ=Europe/Paris date
now()
2022-06-15 18:09:22
Wed 15 Jun 2022 18:09:23 CEST
```

Keep in mind [time_zone](https://mariadb.com/kb/en/server-system-variables/#time_zone) is a Global and Session variable. Meaning if you do `set global time_zone=Europe/Paris`, this doesn't impact the existing sessions, only new sessions/connections made after the global `time_zone` was changed. How are you setting the timezone?

**Comment by iangilfillan** [comment]
4 days out is unlikely to be a timezone issue. Is the time on the actual machine itself correctly set?

**Comment by grooverdan** [comment]
Yep, [A StackOverflow commenter](https://stackoverflow.com/questions/72633724/wrong-time-and-date-with-mariadb-mysql) came to the same conclusion.

Happy to take bug reports, but I don't think this is one.
