### ISSUE TITLE
MariaDB failing to apply migrations yii2

### ISSUE THREAD

**Issue by frarossi300800** [MariaDB/mariadb-docker#443]
Hi, i'm trying to populate a database by running ./yii migrate command, native from yii2 framework. So if i try that on a mysql environment nothing go wrong but if i do the same operation in a MariaDB database procedure starts but at some point it freezes and always hangs on the same table returning this error:

> add primary key  on table_1 (date, id_a, id_b) ...Exception: SQLSTATE[HY000]: General error: 1194 Table 'table_1' is marked as crashed and should be repaired

Whatever if i run a dump of another database already created none error were generated.
I've tried to run some repair commands such as [mysqlrepair -A --auto-repair+ but nothing done

**Comment by grooverdan** [comment]
I'll need some more information. Can you include these in a new [bug report](https://jira.mariadb.org)?

Which mariadb version are you using?

What is the sequence of statements that `./yii migrate` generates that occurs on table_1?

What is the original `show create table table_1`?

Can you show the container logs?

**Comment by frarossi300800** [comment]
just opened issue on jira https://jira.mariadb.org/browse/MDEV-28902
