### ISSUE TITLE
[Support] max_connections 

### ISSUE THREAD

**Issue by pyte1** [MariaDB/mariadb-docker#449]
Hey,

is there a way to set the max_connections setting that usually is set within the my.cnf through an ENV Variable directly from the yaml file, or do i need to mount the config file as a volume with:
`./mysql/scripts/my.cnf:/etc/mysql/my.cnf`

**Comment by grooverdan** [comment]
Use command line arguments, like #445

**Comment by grooverdan** [comment]
Note if mounting config options in a file, use `/etc/mysql/conf.d` per [the docs](https://hub.docker.com/_/mariadb/) ("Using a custom MariaDB configuration file). Maybe I'll reword the docs, so many people are jumping on `/etc/mysql/my.cnf` and not following the rest.
