### ISSUE TITLE
images not update to releases  of 15/08

### ISSUE THREAD

**Issue by olafbuitelaar** [MariaDB/mariadb-docker#455]
It appears, the releases of 10.8.4, 10.7.5 and 10.6.9 aren't getting published.

**Comment by justlevine** [comment]
Stuck on this too.

**Comment by famod** [comment]
Still not available. That's unfortunate given all those critical fixes (in 10.6.9).

/cc @grooverdan

**Comment by grooverdan** [comment]
https://github.com/docker-library/official-images/pull/13008 its coming. There was a delay on the 10.9 (now GA/latest) and 10.10 release.

**Comment by grooverdan** [comment]
released
