### ISSUE TITLE
[documentation] typing special characters in the container shell

### ISSUE THREAD

**Issue by douglas-legulas** [MariaDB/mariadb-docker#468]
When I'm testing some SQL I often need to paste or type it on the terminal, and by default special characters (such as `#`, `é`, `ã`) will not output correctly unless you start the container with a UTF-8 locale set (e.g. `C.UTF-8`).

The Ubuntu image, for example, has this [documented](https://github.com/docker-library/docs/blob/135b79cc8093ab02e55debb61fdb079ab2dbce87/ubuntu/README.md#locales). We could at least add a reference to it in the README.

**Comment by grooverdan** [comment]
If you follow the documentation with `ENV LANG C.UTF-8`, does it make sense to make that the default?

**Comment by grooverdan** [comment]
What do you think of #470? Does this solve the problem without hunting for documentation?

**Comment by grooverdan** [comment]
merged. You shoudn't need to do anything special after next release.
