### ISSUE TITLE
mariabackup target-dir option ignored with partial backup

### ISSUE THREAD

**Issue by dadcoachengineer** [MariaDB/mariadb-docker#474]
When running this backup command, backup files go to target dir no problem.

`mariabackup --backup --target-dir=/backups/current --user=mariabackup --password=XXXXX`

When running this backup command excluding a table, backup files go to /xtrabackup_backupfiles ignoring the target-dir option.

`mariabackup --backup --tables-exclude=states -target-dir=/backups/current --user=mariabackup --password=XXXXX`

**Comment by grooverdan** [comment]
Did you intentionally misses a `-` before `-target-dir` in the partial case? It should be `--target-dir` list your first command.

**Comment by dadcoachengineer** [comment]
Thank you @grooverdan 

Sorry I missed that :smh
