### ISSUE TITLE
Mariadb is not working

### ISSUE THREAD

**Issue by dswtpvtltd** [MariaDB/mariadb-docker#481]
Os: macos ventura
docker version: 4.15.0 (93002)

I am setting up mariadb by using docker-compose.yml and docker-sync.yml

I am trying to connect mysql on docker terminal by using username: root and password: 123456 used in docker-compose.yml file.

```
# mysql -uroot -p
Enter password: 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
# 
```

in my site code I am using details:
host: db
username: root
password: 123456
database: mydatabase

My docker-compose.yml

```version: "3.2"

services:
  db:
    image: mariadb:10.4
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./dockerfile/phpfpm/db-data:/var/lib/mysql
    networks:
      net:

  web:
    build:
      context: .
      dockerfile: ./dockerfile/phpfpm/Dockerfile.web
    hostname: ${COMPOSE_PROJECT_NAME}-web
    ports:
      - "${HTTPS_PORT}:80"
    restart: always
    volumes:
      - ./src/anyboat-com-au:/var/www/html
    networks:
      net:
    depends_on:
      - db
      - cache
      - session
      - search

  search:
    image: elasticsearch:7.17.6
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    hostname: search
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - bootstrap.system_call_filter=false
    networks:
      net:

  cache:
    image: redis:6.2
    restart: always
    ports:
      - "6380:6379"
    hostname: cache
    networks:
      net:

  session:
    image: redis:6.2
    restart: always
    ports:
      - "6381:6379"
    hostname: session
    networks:
      net:

  varnish:
    build:
      context: .
      dockerfile: ./dockerfile/phpfpm/Dockerfile.varnish
      args:
        VARNISH_CONFIG: ${VARNISH_CONFIG}
    hostname: varnish
    ports:
      - "${HTTP_PORT}:6081"
    networks:
      net:
    depends_on:
      - web

networks:
  net:
```

**Comment by grooverdan** [comment]
note in #447, that especially using MacOS that you should be using named volumes. Check your docker /compose logs for the mariadb container show it to be running.

MacOS runs the container in a VM so a unix socket (default) authentication isn't going to pass through to the VM).

In your compose you've exposed it as port 3307.

From from MacOS:
```
$ mysql --port 3307 --user root --host 127.0.0.1 --protocol tcp -p
```

You may also need to

**Comment by dswtpvtltd** [comment]
> note in #447, that especially using MacOS that you should be using named volumes. Check your docker /compose logs for the mariadb container show it to be running.
> 
> MacOS runs the container in a VM so a unix socket (default) authentication isn't going to pass through to the VM).
> 
> In your compose you've exposed it as port 3307.
> 
> From from MacOS:
> 
> ```
> $ mysql --port 3307 --user root --host 127.0.0.1 --protocol tcp -p
> ```
> 
> From existing documents it will be on host 127.0.0.1 but if needed inspect the container to examine its networking setup.

Thanks for your reply. I tried above command but it is still now working
I am getting following response

# mysql --port 3307 --user root --host 127.0.0.1 --protocol tcp -p
Enter password: 
ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115)

Please check the following image URl for inspect
<img width="956" alt="Screenshot 2022-12-21 at 10 39 10 AM" src="https://user-images.githubusercontent.com/3082270/208826455-1b22c933-8f4f-4e4c-bb7c-8d5df51d7a47.png">

**Comment by grooverdan** [comment]
I searched though https://jira.mariadb.org and have been unable to find and existing bug report.

Can you please create a new bug report. I assume anyboat_m2 corresponds to a tablename in some form. Include `show create table {tablename}` in your bug report if you have a definition from somewhere that's not corrupted.

If you are willing to share privately your datadir zipped up for MariaDB developers that would also aid debugging this. use the [ftp server](https://mariadb.com/kb/en/meta/mariadb-ftp-server/) and make a note its there in your bug report.

**Comment by dswtpvtltd** [comment]
> I searched though https://jira.mariadb.org and have been unable to find and existing bug report.
> 
> Can you please create a new bug report. I assume anyboat_m2 corresponds to a tablename in some form. Include `show create table {tablename}` in your bug report if you have a definition from somewhere that's not corrupted.
> 
> If you are willing to share privately your datadir zipped up for MariaDB developers that would also aid debugging this. use the [ftp server](https://mariadb.com/kb/en/meta/mariadb-ftp-server/) and make a note its there in your bug report.

Thanks you very much to reply me.
Sir, I am unable to connect to mariaDB either by terminal or by any GUI tools it is not possble to create database yet. and As I know that when we pass database by environment: - MYSQL_DATABASE=mydatabase, it will create an empty database. current databases it is empty. there are no any table or data and I have to create this new database.

**Comment by grooverdan** [comment]
You're unable to connect because MariaDB didn't start. MariaDB failed because of what was in the logs, which was as a result of a pre-mariadb-10.4 data stored in `./dockerfile/phpfpm/db-data`. Because this isn't an empty directory its not even going to try to create a new database.

https://docs.docker.com/desktop/mac/ recommends using named volume/data container for database volumes. Is there are reason you aren't doing this? With a new project seems like a good time to use a *named* volume rather than a local path.
