### ISSUE TITLE
release 10.11.2 stable

### ISSUE THREAD

**Issue by inductor** [MariaDB/mariadb-docker#489]
ref. https://mariadb.org/mariadb/all-releases/

**Comment by grooverdan** [comment]
Watch for progress https://github.com/docker-library/official-images/pull/14111

After merged it still takes a little time to show up. See [faq](https://github.com/MariaDB/mariadb-docker#i-see-a-change-merged-here-that-hasnt-shown-up-on-docker-hub-yet).

**Comment by grooverdan** [comment]
https://hub.docker.com/_/mariadb/
