### ISSUE TITLE
Missing symlink to mysqldump?

### ISSUE THREAD

**Issue by tushev** [MariaDB/mariadb-docker#519]
I'm trying to execute the following command:

```
 docker compose exec db sh -c 'exec mysqldump --all-databases -uroot -p"R00tPASSw0RD"'
```
But I get the following error: `sh: 1: exec: mysqldump: not found`.

In the same time, `mariadb-dump` works.

Is [symlink to mysqldump missing](https://mariadb.com/kb/en/mysqldump/) in Docker image or it is a deliberate decision?

**Comment by grooverdan** [comment]
It is deliberately missing in in the mariadb:latest (11.0). ref: #512.

It was time we started to get referred to by our own name.

Sorry for the inconvenience and thanks for using MariaDB.

**Comment by tushev** [comment]
OK, thank you for explaining. For consistency, please consider adding a disclaimer here: https://mariadb.com/kb/en/mysqldump/

**Comment by grooverdan** [comment]
Done. Added a notice in addition to it being in a Legacy Clients and Utilities category. Thanks.
