### ISSUE TITLE
Disabling skip-name-resolve not working as expected

### ISSUE THREAD

**Issue by Jerre1990** [MariaDB/mariadb-docker#525]
According to the documentation there are currently three ways to disable the skip-name-resolve feature (which is enabled by default), all of which do not work:
- add the option in a custom configuration file in the /etc/mysql/conf.d directory. This does not work, because that config gets overruled by the default one, which is located at _/etc/mysql/mariadb.conf.d/05-skipcache.cnf_.
- add _disable-skip-name-resolve_ as an environment variable. This throws an error during container initialization, stating that an option was found without a preceding group in the config file _/etc/mysql/conf.d/disable-skip-name-resolve.cnf_.
- add _disable-skip-name-resolve_ as an argument for the entrypoint script. This throws the same error during container initialization.

**Comment by Jerre1990** [comment]
Turns out some options were conflicting with each other. Isolating them fixed the issue. Documentation seems ok.

**Comment by grooverdan** [comment]
once [MDEV-31323](https://jira.mariadb.org/browse/MDEV-31323) is implemented in the server I can remove /etc/mysql/mariadb.conf.d/05-skipcache.cnf with little consequence.
