### ISSUE TITLE
MDEV-32008 MariaDB 10.11: Auto Increment behavior

### ISSUE THREAD

**Issue by Nezisi** [MariaDB/mariadb-docker#527]
Hi, I'm seeing a very strange behavior only in MariaDB 10.11, previous MariaDB LTS version 10.6 doesn't exhibit the behavior.

What's happening:
- we use a Dockerfile to copy an SQL file
- docker-entrypoint script runs the import
- added SHOW CREATE TABLE to the SQL file shows that the auto-increment value is correct

After finishing, the server shuts down. 

The next time the server starts, the auto-increment values of all tables were incremented by one.

We've set innodb_flush_log_at_trx_commit = 1. Additionally I disabled aio_async, tried to use fsync and set innodb_fast_shutdown=0 as I suspected some kind of database corruption...

Anyone got an idea what is happening?

**Comment by grooverdan** [comment]
Can you attach a minimal example of the SQL file?

**Comment by dr-m** [comment]
Could this have been fixed by MariaDB/server@4700f2ac70f8c79f2ac1968b6b59d18716f492bf?

**Comment by grooverdan** [comment]
quite right - regression to the commit noted by @dr-m. https://jira.mariadb.org/browse/MDEV-32008 for upstream bug.

**Comment by grooverdan** [comment]
and @Thirunarayanan for fixing it :-)

**Comment by grooverdan** [comment]
10.11.6 is now released and available as a container. Thanks for reporting this bug.
