### ISSUE TITLE
MariaDB 11.1.2 image incorrectly marked rc?

### ISSUE THREAD

**Issue by evanelias** [MariaDB/mariadb-docker#529]
On https://hub.docker.com/_/mariadb/tags, 11.1.2 is tagged as a release candidate ("11.1.2-rc"), and meanwhile "latest" currently still points to 11.0.3.

But according to https://mariadb.com/kb/en/mariadb-11-1-2-release-notes/, MariaDB 11.1 is now considered generally available, since 11.1.2 was a stable / GA release.

I assume this was just an oversight in #526, can anyone confirm? Thank you -- looking forward to trying 11.1!

**Comment by grooverdan** [comment]
yep, was a mistake. It will be corrected in the next few days.

**Comment by grooverdan** [comment]
corrected now.

**Comment by evanelias** [comment]
Much appreciated, thanks!
