### ISSUE TITLE
Missing mysqldump symlink for mariadb-dump

### ISSUE THREAD

**Issue by martymonero** [MariaDB/mariadb-docker#530]
According to https://mariadb.com/kb/en/mariadb-dump/ there should be a mysqldump symlink for the new mariadb-dump. I could not find it in the new Docker Images.

**Comment by grooverdan** [comment]
And https://mariadb.com/kb/en/mysqldump/ says the symlink is deprecated and removed. Yes I'll make the docs consistent.

**Comment by grooverdan** [comment]
Thanks @iangilfillan (doc edit)  :-)

dup #519
