### ISSUE TITLE
Image changes over time on the same image tag

### ISSUE THREAD

**Issue by adrianandreias** [MariaDB/mariadb-docker#535]
Looks like the actual image changes over time for the same image tag (`10.11.5-jammy`). Here are 3 different machines with the image pulled at different points in time:

```
docker image ls|grep mariadb|grep 10.11.5-jammy
mariadb                                      10.11.5-jammy   f3ccb05c76f7   4 days ago     403MB
```

```
mariadb                                      10.11.5-jammy   58df8de36e1c   6 weeks ago     403MB
```

```
mariadb                                      10.11.5-jammy   32c5888d2fa9   2 weeks ago    403MB
```

The problem is that some of the images have `mysqldump` and some do not.

Is this intentional? Is there some other tag that can be used to lock the actual image for one tag and do not have it changed over time?

**Comment by grooverdan** [comment]
Odd, release history is https://github.com/docker-library/official-images/commits/master/library/mariadb

rebuilds happen (ubuntu releases normally) - https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/mariadb/ - haven't found enough detail to see build logs.

11.0+ will remove the mysqldump symlink. mariadb-dump will still be there and in older versions too.

I don't have a full image list like you so can't verify this myself.

**Comment by grooverdan** [comment]
Found it, I think you had images before https://github.com/docker-library/official-images/pull/14936 and https://github.com/docker-library/official-images/pull/14797 (17 days earlier).
