### ISSUE TITLE
Latest image doesn't have symbolic link from /usr/bin/mysql to /usr/bin/mariadb

### ISSUE THREAD

**Issue by Simpler1** [MariaDB/mariadb-docker#545]
In the recent past, the following symbolic link was already created in the mariadb image:

`ln -s /usr/bin/mariadb /usr/bin/mysql`

This is a regression and causes other images that are built on top of mariadb to fail.

Please consider add thing back to the base image.

**Comment by grooverdan** [comment]
see #514 and https://mariadb.org/mariadb-server-docker-official-images-healthcheck-without-mysqladmin/

No-one moves off compatibility symlinks unless removed. Most cases so far have been improper healthcheck tests as the blog indicates. While there are some valid uses, there's compatible functionality that has existed for many years.

Sorry, I still haven't seen a major case for reverting this symlink. We're not MySQL, and legacy compatibility implications need to be severed at some point.

Sorry for your difficulties.

**Comment by Simpler1** [comment]
That makes sense.  I thought it might have been an oversight.  I can work around this now that I know that it is intended.

Thanks
