### ISSUE TITLE
mariadb Import error 

### ISSUE THREAD

**Issue by talalahmad1** [MariaDB/mariadb-docker#549]
ERROR 1064 (42000) at line 1862820: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''[event_count]         \n                       <a href=\"#reguser\" role=\"button\">\n                         <svg aria-hid...' at line 2

**Comment by grooverdan** [comment]
This isn't a support forum - lets continue where you [originally posted](https://stackoverflow.com/questions/77721168/import-issue-in-mariadb-database-while-importing-wordpress-data-in-linux-termina). Answer comment questions by editing the question.
