### ISSUE TITLE
Request for MariaDB Image Compatible with ARMv6 for Raspberry Pi Zero

### ISSUE THREAD

**Issue by showf68** [MariaDB/mariadb-docker#550]
Hello,

I am attempting to install MariaDB on a Raspberry Pi Zero, which operates on an ARMv6 architecture. Currently, there seems to be a lack of available images that are compatible with this particular architecture.

Would it be possible for the MariaDB Docker image maintainers to provide an official image for ARMv6, or alternatively, could you provide a Dockerfile that I can use to build MariaDB for ARMv6?

I understand that ARMv6 is less common these days and maintaining images for it might not be a priority, but support for this architecture would be incredibly beneficial for those of us working with devices like the Raspberry Pi Zero.

Thank you very much for considering my request.

Best regards,
showf

**Comment by grooverdan** [comment]
Sorry can't do it. Simply too much effort and no hardware that can be used for CI testing.

https://ricardodeazambuja.com/rpi/2020/12/29/rpi2docker/ is probably a start. 

Debian does [armel MariaDB packages](https://packages.debian.org/bookworm/mariadb-server-core), though I have doubts they [actually are built correctly](https://github.com/MariaDB/server/pull/2896), do check as a first step. I couldn't find a v6 Debian image, after which should be reasonably easy to create a container:
```diff
diff --git a/10.11/Dockerfile b/10.11/Dockerfile
index 042831d..1a13263 100644
--- a/10.11/Dockerfile
+++ b/10.11/Dockerfile
@@ -1,5 +1,5 @@
 # vim:set ft=dockerfile:
-FROM ubuntu:jammy
+FROM debian:12
 
 # add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
 RUN groupadd -r mysql && useradd -r -g mysql mysql --home-dir /var/lib/mysql
@@ -79,22 +79,12 @@ LABEL org.opencontainers.image.authors="MariaDB Community" \
       org.opencontainers.image.url="https://github.com/MariaDB/mariadb-docker"
 
 # bashbrew-architectures: amd64 arm64v8 ppc64le s390x
-ARG MARIADB_VERSION=1:10.11.6+maria~ubu2204
+ARG MARIADB_VERSION=1:10.11.6
 ENV MARIADB_VERSION $MARIADB_VERSION
 # release-status:Stable
 # release-support-type:Long Term Support
 # (https://downloads.mariadb.org/rest-api/mariadb/)
 
-# Allowing overriding of REPOSITORY, a URL that includes suite and component for testing and Enterprise Versions
-ARG REPOSITORY="http://archive.mariadb.org/mariadb-10.11.6/repo/ubuntu/ jammy main main/debug"
-
-RUN set -e;\
-       echo "deb ${REPOSITORY}" > /etc/apt/sources.list.d/mariadb.list; \
-       { \
-               echo 'Package: *'; \
-               echo 'Pin: release o=MariaDB'; \
-               echo 'Pin-Priority: 999'; \
-       } > /etc/apt/preferences.d/mariadb
 # add repository pinning to make sure dependencies from this MariaDB repo are preferred over Debian dependencies
 #  libmariadbclient18 : Depends: libmysqlclient18 (= 5.5.42+maria-1~wheezy) but 5.5.43-0+deb7u1 is to be installed
 
```
