### ISSUE TITLE
There is a strange error when trying to recreate a table after deleting it.

### ISSUE THREAD

**Issue by Soo-yeong** [MariaDB/mariadb-docker#569]
If you accidentally create a table with the same name first and then do a drop table, even if the drop table succeeds, it will appear as a table that already exists when you create a table later. 
The problem is that this problem is solved only by restarting the server without eating Flush Tables.
 Please solve it! Or I hope you can tell me how I can solve this problem.

**Comment by grooverdan** [comment]
> If you accidentally create a table with the same name first and then do a drop table, even if the drop table succeeds, it will appear as a table that already exists when you create a table later.

How?

> The problem is that this problem is solved only by restarting the server without eating Flush Tables.

> Please solve it!
> Or I hope you can tell me how I can solve this problem.

Provide a detailed reproducer - exact SQL commands and there reponses. Include the MariaDB version. "strange error" isn't that specific.
