### ISSUE TITLE
Why is there no 10.5.25 or 10.6.18

### ISSUE THREAD

**Issue by frob** [MariaDB/mariadb-docker#577]
It looks like the docker images stop at version 10.5.24 and 10.6.17 are the docker images not kept up to date with the native releases?

**Comment by grooverdan** [comment]
I was waiting for the 11.4 version to come out too, but as of Friday that's still got one thing to fix.

As 11.3 has gone, doing a release not would means the latest tag goes from 11.3 back to 11.2, which would cause problems.

While I could do a few hacks to get 11.3 back on its previous version I'm going wait 1-2 days for a 11.4 to come out before release.

**Comment by jonlil** [comment]
Hello,

Not sure if this is related but the merge to master 16 hours ago seems to have some failures, I was looking for version 10.11.8 but could not find it.
https://github.com/MariaDB/mariadb-docker/actions/runs/9151705008/job/25158138477

**Comment by grooverdan** [comment]
there merge to master is failing because the 11.4 isn't there yet. Hopefully soon, or I'll do a workaround to get all the other releases out on Docker Official Images.

**Comment by jgb** [comment]
Same question here: in need of 10.11.8, thanks!

**Comment by grooverdan** [comment]
FYI this PR - https://github.com/docker-library/official-images/pull/16821 will need to merge first, and after the build process in the Docker Official Images infrastructure, the release will be available.

**Comment by grooverdan** [comment]
its released now.
