### ISSUE TITLE
Missing arm64 builds and wrong lts version

### ISSUE THREAD

**Issue by thueske** [MariaDB/mariadb-docker#590]
The arm64 builds in the 11.4 tag seem to be missing:
<img width="1176" alt="Bildschirmfoto 2024-05-31 um 07 19 00" src="https://github.com/MariaDB/mariadb-docker/assets/436986/c09a0b15-3d15-4790-8e80-a83573e6dc85">

<img width="1173" alt="Bildschirmfoto 2024-05-31 um 07 19 13" src="https://github.com/MariaDB/mariadb-docker/assets/436986/1224b1d4-98b8-45e6-8c07-d8bd81eeab74">

**Comment by thueske** [comment]
Also, the LTS tag seems to be wrong. It still starts the old MariaDB version and not the new LTS 11.4 - is this intended?

```
> docker pull mariadb:lts
lts: Pulling from library/mariadb
d5a2ad729c09: Pull complete
dc56fc8d32a5: Pull complete
f42de1ff02cc: Pull complete
8cc2f8eb89fa: Pull complete
9bff9185e82b: Pull complete
d90e0f4f1401: Pull complete
c5108c7d84d8: Pull complete
0224b2ce27d0: Pull complete
Digest: sha256:56c9ba9e5f078bd66548b12415d81073f35ad1dd26e9171062cc78b07ebde9f7
Status: Downloaded newer image for mariadb:lts
docker.io/library/mariadb:lts

> docker run docker.io/library/mariadb:lts
2024-05-31 05:24:18+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.11.8+maria~ubu2204 started.
2024-05-31 05:24:18+00:00 [Warn] [Entrypoint]: /sys/fs/cgroup///memory.pressure not writable, functionality unavailable to MariaDB
```

**Comment by grooverdan** [comment]
Arm64 should be there - raised https://github.com/docker-library/official-images/issues/16885 - not sure why its missing.

Yes 11.4 is LTS - https://mariadb.org/mariadb-11-4-2-and-mariadb-11-5-1-now-available/

**Comment by grooverdan** [comment]
> Also, the LTS tag seems to be wrong. It still starts the old MariaDB version and not the new LTS 11.4 - is this intended?
> 

```
$ podman pull mariadb:lts
$ podman run --rm mariadb:lts --help ---version
mariadbd  Ver 11.4.2-MariaDB-ubu2404 for debian-linux-gnu on x86_64 (mariadb.org binary distribution)

$ podman pull --arch arm64  mariadb:lts
$ podman run --rm mariadb:lts --help ---version
WARNING: image platform (linux/arm64) does not match the expected platform (linux/amd64)
/usr/sbin/mariadbd  Ver 10.11.8-MariaDB-ubu2204 for debian-linux-gnu on aarch64 (mariadb.org binary distribution)
```

Seems like a safe fallback if the arch is missing. Once resolve hopefully back to 11.4. Hope it goes smoothly for you.

**Comment by thueske** [comment]
Works now 👍🏻 Thank you
