### ISSUE TITLE
Signal 11 (Segmentation Fault) [ERROR] mysqld got signal 11 in mariadb 

### ISSUE THREAD

**Issue by orangeabraham** [MariaDB/mariadb-docker#607]
Signal 11 (Segmentation Fault) [ERROR] mysqld got signal 11 in maria db  server kindly someone help to resolved this error

**Comment by grooverdan** [comment]
Guidance for bug reporting is https://mariadb.com/kb/en/reporting-bugs/.

More information is needed. Start with the complete container logs, from startup if possible. Please create a https://jira.mariadb.org/ bug report and I'll probably ask some more questions to get sufficient information for MariaDB server developers to understand and correct the segfault experienced.

**Comment by grooverdan** [comment]
Looking forward to your bug report. Without it, it will only be fixed if someone else has identified the same issue. Please take the time to report issues found with your free database.

**Comment by grooverdan** [comment]
New releases have been done. If this doesn't correct your problem please do a bug report.
