### ISSUE TITLE
mariadb:11.4-jammy No image?

### ISSUE THREAD

**Issue by mariushosting** [MariaDB/mariadb-docker#611]
There is no Docker image for mariadb:11.4-jammy ?
I see only the RC version available.

**Comment by grooverdan** [comment]
There's an 11.4-noble - https://hub.docker.com/_/mariadb/ - we take the latest Ubuntu LTS at the time of release and keep that for the MariaDB release series.

**Comment by mariushosting** [comment]
> There's an 11.4-noble - https://hub.docker.com/_/mariadb/ - we take the latest Ubuntu LTS at the time of release and keep that for the MariaDB release series.

Will 11.4-jammy not be released anymore?

**Comment by grooverdan** [comment]
I wasn't planning on it. 

> > There's an 11.4-noble - https://hub.docker.com/_/mariadb/ - we take the latest Ubuntu LTS at the time of release and keep that for the MariaDB release series.
> 
> Will 11.4-jammy not be released anymore?

I wasn't planning on it. There's always been only one ubuntu release per version. Is there a reason Noble isn't suitable?

**Comment by mariushosting** [comment]
Yes, noble isn't working 100% correctly on DSM (Synology operating system) and some Docker Containers.

Only the jammy version works perfectly.

**Comment by grooverdan** [comment]
I'm keen to know details, so at least it can be documented or problems avoided in the future.

Could try 11.4-ubi. Its substantial difference is is default is `mysql` as a user instead of `root`. `user: root` is sufficient to make it behave the same way.

**Comment by mariushosting** [comment]
> I'm keen to know details, so at least it can be documented or problems avoided in the future.
> 
> Could try 11.4-ubi. Its substantial difference is is default is `mysql` as a user instead of `root`. `user: root` is sufficient to make it behave the same way.
This is an error that appears randomly on different Synology NAS devices:

MySQL: Access denied for user 'root'@'localhost' (using password: YES)

The issue occurs with standard Mariadb:11.4 and other versions, but never with the :jammy version.

**Comment by grooverdan** [comment]
Might be the changes to healthcheck #610 - I intend to work on this very soon if this is it just trying to access before fully initialized.

Otherwise this can facilitate a build (but might be the same problem)
```
diff --git a/11.4/Dockerfile b/11.4/Dockerfile
index 7fa81d5..6077021 100644
--- a/11.4/Dockerfile
+++ b/11.4/Dockerfile
@@ -1,8 +1,8 @@
 # vim:set ft=dockerfile:
-FROM ubuntu:noble
+FROM ubuntu:jammy
 
 # add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
-RUN groupadd -r mysql && useradd -r -g mysql mysql --home-dir /var/lib/mysql && userdel --remove ubuntu
+RUN groupadd -r mysql && useradd -r -g mysql mysql --home-dir /var/lib/mysql
 
 # add gosu for easy step-down from root
 # https://github.com/tianon/gosu/releases
@@ -71,7 +71,7 @@ LABEL org.opencontainers.image.authors="MariaDB Community" \
       org.opencontainers.image.title="MariaDB Database" \
       org.opencontainers.image.description="MariaDB Database for relational SQL" \
       org.opencontainers.image.documentation="https://hub.docker.com/_/mariadb/" \
-      org.opencontainers.image.base.name="docker.io/library/ubuntu:noble" \
+      org.opencontainers.image.base.name="docker.io/library/ubuntu:jammy" \
       org.opencontainers.image.licenses="GPL-2.0" \
       org.opencontainers.image.source="https://github.com/MariaDB/mariadb-docker" \
       org.opencontainers.image.vendor="MariaDB Community" \
@@ -79,14 +79,14 @@ LABEL org.opencontainers.image.authors="MariaDB Community" \
       org.opencontainers.image.url="https://github.com/MariaDB/mariadb-docker"
 
 # bashbrew-architectures: amd64 arm64v8 ppc64le s390x
-ARG MARIADB_VERSION=1:11.4.3+maria~ubu2404
+ARG MARIADB_VERSION=1:11.4.3+maria~ubu2204
 ENV MARIADB_VERSION $MARIADB_VERSION
 # release-status:Stable
 # release-support-type:Long Term Support
 # (https://downloads.mariadb.org/rest-api/mariadb/)
 
 # Allowing overriding of REPOSITORY, a URL that includes suite and component for testing and Enterprise Versions
-ARG REPOSITORY="http://archive.mariadb.org/mariadb-11.4.3/repo/ubuntu/ noble main main/debug"
+ARG REPOSITORY="http://archive.mariadb.org/mariadb-11.4.3/repo/ubuntu/ jammy main main/debug"
 
 RUN set -e;\
        echo "deb ${REPOSITORY}" > /etc/apt/sources.list.d/mariadb.list; \
```

**Comment by mariushosting** [comment]
> Might be the changes to healthcheck #610 - I intend to work on this very soon if this is it just trying to access before fully initialized.
> 
> Otherwise this can facilitate a build (but might be the same problem)
> 
> ```
> diff --git a/11.4/Dockerfile b/11.4/Dockerfile
> index 7fa81d5..6077021 100644
> --- a/11.4/Dockerfile
> +++ b/11.4/Dockerfile
> @@ -1,8 +1,8 @@
>  # vim:set ft=dockerfile:
> -FROM ubuntu:noble
> +FROM ubuntu:jammy
>  
>  # add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
> -RUN groupadd -r mysql && useradd -r -g mysql mysql --home-dir /var/lib/mysql && userdel --remove ubuntu
> +RUN groupadd -r mysql && useradd -r -g mysql mysql --home-dir /var/lib/mysql
>  
>  # add gosu for easy step-down from root
>  # https://github.com/tianon/gosu/releases
> @@ -71,7 +71,7 @@ LABEL org.opencontainers.image.authors="MariaDB Community" \
>        org.opencontainers.image.title="MariaDB Database" \
>        org.opencontainers.image.description="MariaDB Database for relational SQL" \
>        org.opencontainers.image.documentation="https://hub.docker.com/_/mariadb/" \
> -      org.opencontainers.image.base.name="docker.io/library/ubuntu:noble" \
> +      org.opencontainers.image.base.name="docker.io/library/ubuntu:jammy" \
>        org.opencontainers.image.licenses="GPL-2.0" \
>        org.opencontainers.image.source="https://github.com/MariaDB/mariadb-docker" \
>        org.opencontainers.image.vendor="MariaDB Community" \
> @@ -79,14 +79,14 @@ LABEL org.opencontainers.image.authors="MariaDB Community" \
>        org.opencontainers.image.url="https://github.com/MariaDB/mariadb-docker"
>  
>  # bashbrew-architectures: amd64 arm64v8 ppc64le s390x
> -ARG MARIADB_VERSION=1:11.4.3+maria~ubu2404
> +ARG MARIADB_VERSION=1:11.4.3+maria~ubu2204
>  ENV MARIADB_VERSION $MARIADB_VERSION
>  # release-status:Stable
>  # release-support-type:Long Term Support
>  # (https://downloads.mariadb.org/rest-api/mariadb/)
>  
>  # Allowing overriding of REPOSITORY, a URL that includes suite and component for testing and Enterprise Versions
> -ARG REPOSITORY="http://archive.mariadb.org/mariadb-11.4.3/repo/ubuntu/ noble main main/debug"
> +ARG REPOSITORY="http://archive.mariadb.org/mariadb-11.4.3/repo/ubuntu/ jammy main main/debug"
>  
>  RUN set -e;\
>         echo "deb ${REPOSITORY}" > /etc/apt/sources.list.d/mariadb.list; \
> ```

This is the exact issue I'm seeing

**Comment by grooverdan** [comment]
For testing ghcr.io/mariadb/mariadb:11.5.2-noble

https://github.com/docker-library/official-images/pull/17468 has the official change.

**Comment by mariushosting** [comment]
> For testing ghcr.io/mariadb/mariadb:11.5.2-noble
> 
> [docker-library/official-images#17468](https://github.com/docker-library/official-images/pull/17468) has the official change.

works like a charm!

**Comment by grooverdan** [comment]
@mariushosting, thank for confirming. Much appreciated.
