### ISSUE TITLE
Galera gcs_proto_ver downgraded on MariaDB 11+

### ISSUE THREAD

**Issue by betaphi** [MariaDB/mariadb-docker#616]
When trying to update my Galera Cluster from MariaDB version 10.11 to 11.0 (and up), I get an error on the updated node while it tries to join the existing cluster:

`
2024-10-07 10:56:46 0 [ERROR] WSREP: ./gcs/src/gcs_group.cpp:group_check_proto_ver():341: Group requested gcs_proto_ver: 4, max supported by this node: 3.Upgrade the node before joining this group.Need to abort.
`

To me, it reads like the existing nodes in the cluster run version 4 of `gcs_proto_ver` but the one that is trying to join only runs version 3. This is strange, as I would suspect the new version of the MariaDB container to come with the latest version of Galera as well.

Is this a known issue?

**Comment by grooverdan** [comment]
It does look like your description is right.

gcs proto version was bumped in https://github.com/mariaDB/galera/commit/91f0090a05e96c3cc353b80d961ede45cefb9279#diff-dbc1b84ee7a13520e8ec09ccdd2fcbc65a28f9b5f4c66563e76f8b9c3d83ca29 very recently so will only be in the latest release.

Note by tags its in 26.4.19

Container versions:
```
$ podman run --rm  mariadb:10.11 dpkg -l | grep galera
ii  galera-4                26.4.19-ubu2204                         amd64        Replication framework for transactional applications

$ podman run --rm  mariadb:11.4 dpkg -l | grep galera
ii  galera-4                 26.4.19-ubu2404             amd64        Replication framework for transactional applications
```

If you're behind a version you'll be out of date:
```
$ podman run --rm  mariadb:10.11.8 dpkg -l | grep galera
ii  galera-4                26.4.18-ubu2204                         amd64        Replication framework for transactional applications
```

So bumping may work.

I'm not terribly happy with the way container upgrades work for Galera. I can't see a way a full SST will reliably work. So if you can share some good/bad experiences as to what does/doesn't work that would be useful to put into the documentation.

**Comment by grooverdan** [comment]
Note the 11.0 latest, 11.0.6, when EOL before the new galera version was added.

Watch the currently maintained versions - https://mariadb.org/about/#maintenance-policy hence listing 11.4 above.

```
$  podman run --rm  mariadb:11.0.6 dpkg -l | grep galera
ii  galera-4                26.4.18-ubu2204                         amd64        Replication framework for transactional applications
```

**Comment by PascalHoenisch** [comment]
Had the same issue with a newer Version `galera-4/now 26.4.25`.
However the root cause was not setting the patch version of the mariadb container (only `mariadb:10.11`). This lead to the master node updating its image to the newest version (10.11.16), whereas the other two were still on 10.11.15. Because the [GCS_PROTO_MAX](https://github.com/MariaDB/galera/blob/release_26.4.24/gcs/src/gcs_act_proto.hpp#L32C9-L32C22) number changed as @grooverdan described, the other two could not boot anymore, giving the version mismatch error.

Pinning the minor version to `mariadb:10.11.16` and rerrunning the helm update cmd solved it for me.

**Comment by grooverdan** [comment]
😬  - https://github.com/MariaDB/galera/commit/0f34ba2b6053c8954b17ac186004f9600acbb0c6

I'll also draw your attention to https://github.com/MariaDB/server/commit/a865a7c23bd8c06bf1de0a759703f898f6c180c2 which is effectively removing galera as a container option from 12.3+.

@betaphi @PascalHoenisch , I welcome any comments on your current use of galera and impacts this has.
