### ISSUE TITLE
11.5 dockerfiles disappeared before 11.6 got a stable release

### ISSUE THREAD

**Issue by dirkmueller** [MariaDB/mariadb-docker#619]
Hi, recently our SLE BCI container pipeline broke, likely due to https://github.com/MariaDB/mariadb-docker/commit/e4156145dd549a1d100734a13d3db8960fe7905b which removed the 11.5/ subdirectory in a followon commit. we're not ready to switch to 11.6 yet as it hasn't seen a stable release yet. can the 11.5 be restored until 11.6 is stable or should we fall back to the 11.4 files if 11.5 is removed?

**Comment by grooverdan** [comment]
Yep, I hurt myself with its removal too delaying the container releases. Sorry. 11.6.2 stable has been built and is being uploaded to mirrors and forming the package repos around it. Should be about 24 hrs more until a 11.6 is there.

**Comment by grooverdan** [comment]
Ok. pushed them back now.
