### ISSUE TITLE
docker compose watch; entrypoint loads bootstrap sql only once

### ISSUE THREAD

**Issue by cas-liszinski** [MariaDB/mariadb-docker#625]
Latest docker/compose, latest mariadb image.

Standard build and run option works ok, but in docker compose watch mode image entrypoint executes query in `/docker-entrypoint-initdb.d/bootstrap.sql` only at first docker compose up run.

Can someone help or suggest?

**Comment by grooverdan** [comment]
I don't know what you mean by "standard build and run option works ok".

The entrypoint is only meant to bootstrap the `/docker-entrypoint-initdb.d` during the initialization of the database.

So as far as I"m concerned  its working as expected.

What functionality are you after and for what purpose? Something like #515?

**Comment by cas-liszinski** [comment]
Thanks for reply.

I need a hint, I am wrong somewhere.

I use docker compose with watch mode - when bootstrap.sql file is changed,
image is rebuilt.

It is not a migrations problem.

First run is ok

```sh
docker compose up --watch --build
```

But any next change of `bootstrap.sql`, starting with second, - I've
checked - invokes creation of container with new bootstrap script - but - I
am really do not understand - entrypoint do not apply the bootstrap script.

But entrypoint must to do, because I am not using volums for now.

**Comment by grooverdan** [comment]
If the contents of the bootstrap file are idpotent perhaps using a configuration [command: --init_file=/docker-entrypoint-initdb.d/bootstrap.sql](https://mariadb.com/kb/en/server-system-variables/#init_file).

**Comment by cas-liszinski** [comment]
Yes, it is idempotent

And thanks for suggestion

But, please, help me to understand

How stateless operation of volumeless container creation can fail?

New image, new container,   where problem can be started?

**Comment by grooverdan** [comment]
> Yes, it is idempotent And thanks for suggestion

> But, please, help me to understand How stateless operation of volumeless container creation can fail? New image, new container, where problem can be started?

If its truly without persistent volumes, and those were empty upon the next initialization, then your bootstrap.sql would be always running. I what you have is a stateful operation, even if not intended. Compose makes volumes persist. There a option to purge them, but by default down/up doesn't clear them.

You aren't providing enough information for me to clearly follow what you are achieving/wanting to see/are actually seeing. More time preparing compose example with markdown formatted logs. Take your time, end of my working day, so if there's a single coherent thought/question/request here for my tomorrow I can answer this. If its vague I won't.

**Comment by cas-liszinski** [comment]
@grooverdan Please, look at ready demo.

https://github.com/cas-liszinski/mariadb-docker-demo

**Comment by cas-liszinski** [comment]
@grooverdan you are right.

But, why volume - i.e. image - not updated by docker compose, when I specify `rebuild` mode?
Have you idea where reasoning can be found?

New file, new image, new volume - where I am wrong?

Maybe, Dockerfile `add` instruction creates a "live" volume, and `bootstrap.sql` is bypassed to the same image - and image remains the same at watch mode rebuilds - something like docker buildkit optimization?

If I am right, how to omit the problem?

**Comment by grooverdan** [comment]
Its actually the first I've come across `rebuild` mode. I don't know. Suggest finding/asking docker-compose folks.

https://docs.docker.com/compose/how-tos/file-watch/#action docs define the exact behaviour.
